"use client";

/**
 * HDSI Core Module Exports
 * 
 * ✅ ALL 20 IMPROVEMENTS IMPLEMENTED
 * 
 * Phase 1: Foundation (5 features)
 * - Virtualized tree rendering
 * - Undo/redo history
 * - IndexedDB persistence
 * - Collaboration (Yjs/WebRTC)
 * - Multi-model configuration
 * 
 * Phase 2: Intelligence (8 features)
 * - Streaming token generation
 * - Vector embeddings/semantic search
 * - RAG context assembly
 * - Dynamic context pruning
 * - Cross-node coherence
 * - Version history
 * - Web Workers ready
 * 
 * Phase 3: Enterprise (7 features)
 * - Domain-specific fine-tuned models
 * - Predictive content generation
 * - Style guide enforcement
 * - Voice interface
 * - Visual diagram generation
 * - Compliance tracker (FAR/DFARS)
 * - Eye tracking integration
 * 
 * NEW: Document Organization System
 * - Smart views and filtering
 * - Folder/workspace hierarchy
 * - Multi-dimensional taxonomy
 * - Template library
 */

// ============================================================================
// Core Types
// ============================================================================
export type {
  HDSINode,
  HDSIDocument,
  HDSIVersion,
  AIModelConfig,
  Command,
  CommandType,
  ModelConfig,
  GenerationOptions,
  GenerationProgress,
  GenerationResult,
  UseHDSIDocumentOptions,
  UseHDSIDocumentResult,
  UseHDSIVersionHistoryResult,
  UseHDSIAllDocumentsResult,
  // Phase 2 Types
  CollaborationSession,
  UserPresence,
  RAGContext,
  RAGSource,
  Citation,
  EmbeddingVector,
  SearchResult,
  TokenStream,
  StreamProgress,
  // Phase 3 Types
  DomainType,
  DomainAdapter,
  DomainGenerationResult,
  PredictionCandidate,
  PredictedContent,
  StyleRule,
  Violation,
  StyleReport,
  VoiceCommand,
  VoiceState,
  DiagramGeneration,
  DiagramType,
  RegulationType,
  RegulationClause,
  ComplianceReport,
  EyePosition,
  AttentionMetrics,
} from "./types";

// ============================================================================
// Phase 1: Foundation
// ============================================================================

// Database (auto-save, versioning, offline sync)
export { hdsiDB } from "./db";

// AI Generation (multi-model, batching)
export {
  generateNodeContent,
  generateBatch,
  generateNodeStreaming,
  generateOutlineFromTemplate,
  createGenerationQueue,
  DEFAULT_CONFIGS,
} from "./ai-generation";

// React Hooks (document management)
export {
  useHDSIDocument,
  useHDSIVersionHistory,
  useHDSIAllDocuments,
} from "./hooks";

// ============================================================================
// Phase 2: Intelligence
// ============================================================================

// Real-time Collaboration
export {
  collaborationManager,
  useCollaboration,
} from "./collaboration";

// Streaming Generation
export {
  streamGeneration,
  simulateStreamingGeneration,
  useStreamingGeneration,
  useTokenVisualization,
} from "./streaming";

// Vector Embeddings
export {
  generateEmbedding,
  generateEmbeddingsForNodes,
  cosineSimilarity,
  findSimilarNodes,
  semanticSearch,
  clusterEmbeddings,
  useEmbeddings,
} from "./embeddings";

// RAG Pipeline
export {
  assembleRAGContext,
  optimizeContext,
  validateCoherence,
  useRAG,
} from "./rag";

// ============================================================================
// Phase 3: Enterprise
// ============================================================================

// 9. Fine-tuned Domain Models
export {
  DOMAIN_ADAPTERS,
  detectDomain,
  detectDomainForNode,
  detectDomainForDocument,
  generateWithDomainAdapter,
  generateWithOptimalDomain,
  useDomainDetection,
  useDomainGeneration,
} from "./domain-models";

// 10. Predictive Content Generation
export {
  predictiveGenerator,
  usePredictiveGeneration,
} from "./predictive";

// 14. Style Guide Engine
export {
  STYLE_PRESETS,
  analyzeStyle,
  useStyleGuide,
  useRealtimeStyleGuide,
} from "./style-guide";

// 17. Voice Interface
export {
  parseVoiceCommand,
  VoiceManager,
  executeVoiceCommand,
  useVoiceInterface,
} from "./voice";

// 18. Visual Diagram Generation
export {
  generateMermaidDiagram,
  generateDalleDiagram,
  generateSvgDiagram,
  autoGenerateDiagram,
  useDiagramGeneration,
  generateDiagramsForDocument,
} from "./diagrams";

// 19. Compliance Tracker
export {
  FAR_CLAUSES,
  DFARS_CLAUSES,
  ALL_CLAUSES,
  detectClauses,
  analyzeCompliance,
  exportTraceabilityMatrix,
  exportComplianceReport,
  useComplianceAnalyzer,
} from "./compliance";

// 20. Eye Tracking
export {
  EyeTrackingManager,
  useEyeTracking,
  useFocusAware,
} from "./eye-tracking";

// ============================================================================
// NEW: Document Organization System
// ============================================================================

// Templates
export {
  ALL_TEMPLATES,
  TEMPLATES_BY_CATEGORY,
  POPULAR_TEMPLATES,
  FAR_PROPOSAL_TEMPLATE,
  DFARS_CYBER_TEMPLATE,
  SBIR_PROPOSAL_TEMPLATE,
  COMMERCIAL_PROPOSAL_TEMPLATE,
  STATEMENT_OF_WORK_TEMPLATE,
  TECHNICAL_SPECIFICATION_TEMPLATE,
  convertTemplateToNodes,
  searchTemplates,
  getTemplateById,
  getSuggestedTemplates,
  type DocumentTemplate,
  type TemplateCategory,
  type TemplateNode,
} from "./templates";

// ============================================================================
// NEW: Advanced Features (5 additions)
// ============================================================================

// 21. Graph View - Force-directed document visualization
export {
  useGraphView,
  buildDocumentGraph,
  getNodeUrl,
  getConnectedNodes,
  getNodeStats,
  DEFAULT_GRAPH_PHYSICS,
  type GraphNode,
  type GraphLink,
  type GraphData,
  type GraphFilters,
  type GraphViewState,
} from "./graph-view";

// 22. AI Diff Preview - Cursor-style edit review
export {
  useAIDiffPreview,
  generateDiff,
  assemblePreviewText,
  assembleFinalText,
  estimateReadingImpact,
  generateChangeExplanation,
  type TextChange,
  type ChangeType,
  type DiffResult,
  type PreviewSession,
  type GranularityOptions,
} from "./ai-diff-preview";

// 23. Speech-to-Text - Voice input for all fields
export {
  useSpeechToText,
  useSpeechInput,
  getListeningIndicatorState,
  createAriaLabelForSpeechButton,
  DEFAULT_SPEECH_COMMANDS,
  SUPPORTED_LANGUAGES,
  type SpeechResult,
  type SpeechCommand,
  type SpeechState,
} from "./speech-to-text";

// 24. Bidirectional Links - [[WikiLinks]] with autocomplete
export {
  useBidirectionalLinks,
  parseBidirectionalLinks,
  detectPartialLink,
  generateLinkSuggestions,
  calculateBacklinks,
  getBacklinksForDocument,
  buildLinkGraph,
  insertLink,
  removeLink,
  LINK_EDITOR_COMMANDS,
  type BidirectionalLink,
  type LinkSuggestion,
  type BacklinkInfo,
  type LinkNode,
} from "./bidirectional-links";

// 25. Text Colors - Colored text and highlighting
export {
  useTextColors,
  getContrastRatio,
  isContrastValid,
  suggestTextColor,
  applySemanticColors,
  formatColorForDom,
  colorToCss,
  parseColorFromCss,
  colorsToMarkdown,
  colorsToLaTeX,
  COLOR_PRESETS,
  SEMANTIC_COLOR_RULES,
  type TextColor,
  type ColoredText,
  type ColorRule,
} from "./text-colors";

// ============================================================================
// 26-34: Publishing & Document Production
// ============================================================================

export {
  usePublishing,
  BIBLIOGRAPHY_STYLES,
  DEFAULT_PAGE_LAYOUT,
  WATERMARK_PRESETS,
  generateLaTeXHeader,
  generateLaTeXFooter,
  pageLayoutToCSS,
  type BibliographyEntry,
  type Citation as BibliographyCitation,
  type CitationStyle,
  type IndexEntry,
  type TOCEntry,
  type TOCOptions,
  type CrossReference,
  type ReferenceTarget,
  type Footnote,
  type MarginNote,
  type Sidebar,
  type PageLayout,
  type PageSize,
  type PageMargins,
  type PageOrientation,
  type Watermark,
  type WatermarkPreset,
  type PageHeader,
  type PageFooter,
  type BibliographyStyle,
} from "./publishing";

// ============================================================================
// Document Export System
// ============================================================================

export {
  useExport,
  exportDocument,
  exportToMarkdown,
  exportToHTML,
  exportToLaTeX,
  exportToPlainText,
  exportToJSON,
  exportToDOCX,
  exportToPDF,
  calculateDocumentStats,
  type ExportFormat,
  type ExportOptions,
  type ExportResult,
  type DocumentListItem,
} from "./export";

// Document Organization
export {
  useDocumentOrganization,
  useDocumentBrowser,
  SMART_VIEWS,
  DEFAULT_FOLDERS,
  createDocumentMetadata,
  matchesFilters,
  sortDocuments,
  groupDocuments,
  type DocumentMetadata,
  type DocumentType,
  type DocumentObjective,
  type DocumentStatus,
  type DocumentStage,
  type Folder,
  type DocumentView,
  type DocumentFilters,
  type SortOption,
  type GroupByOption,
} from "./document-organization";

// ============================================================================
// Presentation System
// ============================================================================

export {
  usePresentations,
  MCKINSEY_THEME,
  BCG_THEME,
  BAIN_THEME,
  THEMES,
  buildSCRStoryline,
  validatePyramidPrinciple,
  type Slide,
  type SlideType,
  type Presentation,
  type PresentationTheme,
  type StorylineFramework,
  type ChartConfig,
  type ChartType,
  type ChartDataPoint,
  type ChartSeries,
  type ChartAnnotation,
  type TableConfig,
  type SCRAnalysis,
  type PyramidValidationResult,
} from "./presentations";

// Presentation Formats (Consulting & Military)
export {
  FORMAT_LIBRARY,
  BCG_FORMAT,
  MCKINSEY_FORMAT,
  BAIN_FORMAT,
  DELOITTE_FORMAT,
  MILITARY_DECISION_BRIEF,
  MILITARY_INFORMATION_BRIEF,
  MILITARY_CONOPS,
  MILITARY_STAFT,
  validateConsultingFormat,
  validateMilitaryFormat,
  generateBCGStoryline,
  generateMilitaryDecisionBrief,
  isActionTitle,
  type FormatType,
  type ConsultingFormat,
  type MilitaryFormatType,
  type ConsultingFirm,
  type FormatValidationResult,
} from "./presentation-formats";
