"""
Opportunity Digest Runner

Entry point for the systemd daily digest job (08:00 UTC).
Reads today's crawl output from storage/opportunities/YYYY-MM-DD.json,
generates an HTML digest via Azure OpenAI, and emails it via Stalwart SMTP.

Usage:
    python -m docfusion.workers.digest [--date YYYY-MM-DD] [--to email@example.com]

Environment variables:
    DIGEST_TO_EMAIL      — recipient address (comma-separated for multiple)
    DIGEST_TO_NAME       — recipient display name
    OPPORTUNITY_STORAGE_DIR — path to daily opportunity JSON files
    SMTP_HOST / SMTP_PORT / SMTP_USER / SMTP_PASSWORD / SMTP_FROM
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

_log = logging.getLogger(__name__)

STORAGE_DIR = Path(os.environ.get("OPPORTUNITY_STORAGE_DIR", "./storage/opportunities"))
DEFAULT_TO_EMAIL = os.environ.get("DIGEST_TO_EMAIL", "")
DEFAULT_TO_NAME = os.environ.get("DIGEST_TO_NAME", "Team")


# ---------------------------------------------------------------------------
# HTML digest builder
# ---------------------------------------------------------------------------

def _html_digest(opportunities: list[dict], date_str: str, summary: str) -> str:
	rows = ""
	for i, opp in enumerate(opportunities[:50], 1):
		title = str(opp.get("title") or "Untitled")
		source = str(opp.get("source") or opp.get("_source") or "")
		url = str(opp.get("source_url") or opp.get("url") or "#")
		org = str(opp.get("organization") or "")
		deadline = str(opp.get("deadline") or "")
		tags = ", ".join(opp.get("tags") or [])
		meta = " · ".join(x for x in [source, org, deadline] if x)
		rows += f"""
		<tr style="border-bottom:1px solid #eee">
		  <td style="padding:8px 4px;color:#555;font-size:12px">{i}</td>
		  <td style="padding:8px">
		    <a href="{url}" style="color:#1a73e8;text-decoration:none;font-weight:500">{title}</a>
		    <div style="color:#777;font-size:12px;margin-top:2px">{meta}</div>
		    {"<div style='color:#999;font-size:11px;margin-top:2px'>" + tags + "</div>" if tags else ""}
		  </td>
		</tr>"""

	return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>DocuFusion Daily Digest — {date_str}</title></head>
<body style="font-family:Arial,sans-serif;max-width:720px;margin:0 auto;padding:20px;color:#333">
  <div style="background:#1a73e8;color:white;padding:16px 20px;border-radius:6px 6px 0 0">
    <h2 style="margin:0">DocuFusion Opportunity Digest</h2>
    <p style="margin:4px 0 0;opacity:.85">{date_str} · {len(opportunities)} new opportunities</p>
  </div>
  <div style="background:#f8f9fa;padding:16px;border-left:3px solid #1a73e8;margin:16px 0">
    <p style="margin:0;line-height:1.5">{summary}</p>
  </div>
  <table style="width:100%;border-collapse:collapse">
    <thead>
      <tr style="background:#f1f3f4">
        <th style="padding:8px 4px;text-align:left;font-size:12px;color:#666">#</th>
        <th style="padding:8px;text-align:left;font-size:12px;color:#666">Opportunity</th>
      </tr>
    </thead>
    <tbody>{rows}</tbody>
  </table>
  <div style="margin-top:24px;padding-top:16px;border-top:1px solid #eee;color:#999;font-size:12px">
    <p>Generated by <strong>DocuFusion</strong> from {len(opportunities)} sources.
    <a href="https://ours.datacraft.systems" style="color:#1a73e8">View dashboard →</a></p>
  </div>
</body>
</html>"""


async def _summarise(opportunities: list[dict]) -> str:
	"""Generate a 2-sentence AI summary of today's opportunities."""
	import httpx
	AZURE_ENDPOINT = (
		"https://lindela.openai.azure.com/openai/deployments/gpt-4.1-mini"
		"/chat/completions?api-version=2024-02-15-preview"
	)
	AZURE_KEY = os.environ.get(
		"AZURE_OPENAI_API_KEY",
		"1qTgOdaDaJUgfgkSllTJlmTptKNv2wdRpRHLoipIh2nWCWBP2qDaJQQJ99BLACYeBjFXJ3w3AAABACOGNs03",
	)
	titles = "\n".join(f"- {o.get('title','')}" for o in opportunities[:20])
	prompt = (
		"Write a 2-sentence executive summary of these new procurement opportunities "
		"discovered today. Focus on themes, sectors, and geographic coverage. "
		f"Be specific.\n\nOpportunities:\n{titles}"
	)
	try:
		async with httpx.AsyncClient(timeout=20) as c:
			r = await c.post(AZURE_ENDPOINT, headers={"api-key": AZURE_KEY},
				json={"messages": [{"role": "user", "content": prompt}],
					  "temperature": 0.3, "max_tokens": 150})
			return r.json()["choices"][0]["message"]["content"].strip()
	except Exception:
		sources = set(o.get("source", "") for o in opportunities if o.get("source"))
		return (
			f"Today's digest contains {len(opportunities)} new procurement opportunities "
			f"from {len(sources)} sources. Review the listings below for deadlines and application details."
		)


def _send_email(to_email: str, to_name: str, subject: str, html: str) -> bool:
	"""Send via Stalwart SMTP using the existing EmailService config."""
	import smtplib
	from email.mime.multipart import MIMEMultipart
	from email.mime.text import MIMEText
	from docfusion.config.secrets import SecretsManager

	host = SecretsManager.get_smtp_host()
	port = SecretsManager.get_smtp_port()
	user = SecretsManager.get_smtp_user()
	password = SecretsManager.get_smtp_password()
	from_addr = SecretsManager.get_smtp_from_address()

	if not host or not from_addr:
		_log.warning("SMTP not configured — skipping email send")
		return False

	msg = MIMEMultipart("alternative")
	msg["Subject"] = subject
	msg["From"] = f"DocuFusion <{from_addr}>"
	msg["To"] = f"{to_name} <{to_email}>" if to_name else to_email
	msg.attach(MIMEText(html, "html", "utf-8"))

	try:
		with smtplib.SMTP(host, port, timeout=30) as smtp:
			smtp.ehlo()
			if port != 25:
				smtp.starttls()
			if user and password:
				smtp.login(user, password)
			smtp.sendmail(from_addr, [to_email], msg.as_string())
		_log.info("Digest email sent to %s", to_email)
		return True
	except Exception as exc:
		_log.error("SMTP send failed: %s", exc)
		return False


# ---------------------------------------------------------------------------
# Main digest logic
# ---------------------------------------------------------------------------

async def run_digest(date_str: str | None = None, to_email: str = "", to_name: str = "") -> int:
	"""Load opportunities for date, summarise, email. Returns count sent."""
	today = date_str or datetime.now(timezone.utc).strftime("%Y-%m-%d")
	path = STORAGE_DIR / f"{today}.json"

	if not path.exists():
		_log.warning("No opportunity file for %s — nothing to digest", today)
		return 0

	with path.open() as f:
		opportunities: list[dict] = json.load(f)

	if not opportunities:
		_log.info("Empty opportunity file for %s", today)
		return 0

	_log.info("Loaded %d opportunities for %s", len(opportunities), today)

	summary = await _summarise(opportunities)
	html = _html_digest(opportunities, today, summary)

	recipients = [e.strip() for e in (to_email or DEFAULT_TO_EMAIL).split(",") if e.strip()]
	if not recipients:
		# Write digest HTML to disk when no recipients configured
		out = STORAGE_DIR / f"{today}-digest.html"
		out.write_text(html, encoding="utf-8")
		_log.info("No DIGEST_TO_EMAIL set — digest written to %s", out)
		return len(opportunities)

	sent = 0
	name = to_name or DEFAULT_TO_NAME
	subject = f"[DocuFusion] {len(opportunities)} new opportunities — {today}"
	for email in recipients:
		if _send_email(email, name, subject, html):
			sent += 1

	_log.info("Digest sent to %d/%d recipients", sent, len(recipients))
	return len(opportunities)


def main() -> int:
	logging.basicConfig(
		level=logging.INFO,
		format="%(asctime)s %(levelname)s %(name)s: %(message)s",
	)
	parser = argparse.ArgumentParser(description="Send daily opportunity digest email")
	parser.add_argument("--date", help="Date to digest (YYYY-MM-DD, defaults to today)")
	parser.add_argument("--to", help="Recipient email (overrides DIGEST_TO_EMAIL env var)")
	parser.add_argument("--name", help="Recipient name", default="")
	args = parser.parse_args()

	try:
		count = asyncio.run(run_digest(args.date, args.to or "", args.name))
		print(f"Digest complete: {count} opportunities sent")
		return 0
	except Exception as exc:
		_log.exception("Digest runner failed: %s", exc)
		return 1


if __name__ == "__main__":
	sys.exit(main())
