import { describe, expect, it } from "vitest";

import {
	DEFAULT_DISCOVERY_QUERIES,
	DEFAULT_DISCOVERY_SEARCH_ENGINES,
	DEFAULT_DISCOVERY_SOURCE_URLS,
	withDefaultDiscoveryRuntimeOptions,
} from "@/lib/services/default-discovery-sources";

describe("default discovery sources", () => {
	it("preloads broad RFP queries plus live-proven and browser-fallback-capable procurement sources", () => {
		expect(DEFAULT_DISCOVERY_QUERIES).toEqual([
			"\"request for proposals\" submission deadline",
			"\"request for proposal\" procurement deadline",
			"\"tender notice\" procurement deadline",
			"\"invitation to bid\" procurement deadline",
			"\"expression of interest\" consultancy deadline",
			"\"terms of reference\" consultancy procurement",
			"\"request for quotations\" procurement deadline",
			"\"request for proposals\" Africa submission deadline",
			"\"request for proposal\" consultancy Africa procurement",
			"\"tender notice\" Africa ICT procurement",
			"\"software development\" tender procurement Africa",
			"\"digital transformation\" \"request for proposals\" Africa",
			"\"grant management system\" tender Africa",
			"\"health information system\" \"request for proposals\" Africa",
			"\"expression of interest\" consultancy services Africa deadline",
			"\"monitoring and evaluation\" \"request for proposals\" Africa deadline",
			"\"data platform\" \"request for proposals\" Africa deadline",
			"\"ERP implementation\" tender Africa deadline",
			"\"cybersecurity\" tender Africa deadline",
			"\"supply and installation\" ICT equipment tender Africa",
			"\"consulting services\" \"expression of interest\" Africa deadline",
			"\"digital health\" \"call for proposals\" Africa deadline",
			"site:ungm.org \"Request for Proposal\"",
			"site:unops.org \"request for proposals\" procurement",
			"site:iom.int \"procurement opportunities\" \"request for proposals\"",
			"site:wfp.org procurement \"request for proposal\"",
			"site:who.int procurement \"request for proposals\"",
			"site:ilo.org procurement \"request for proposal\"",
			"site:ifad.org procurement \"request for proposals\"",
			"site:unhcr.org \"bidding opportunities\" procurement",
			"site:fao.org procurement \"request for proposal\"",
			"site:unwomen.org \"Request for Proposal\" procurement",
			"site:unesco.org procurement \"request for proposal\"",
			"site:theglobalfund.org \"request for proposals\" sourcing",
			"site:unicef.org/supply \"request for proposals\"",
			"site:procurement-notices.undp.org \"RFP\"",
			"site:worldbank.org procurement \"Request for Bids\"",
			"site:worldbank.org \"consulting services\" \"expression of interest\"",
			"site:afdb.org procurement \"request for proposals\"",
			"site:adb.org \"Request for Proposal\" procurement",
			"site:au.int/en/bids African Union bid deadline",
			"site:caribank.org/work-with-us/procurement/procurement-notices \"Deadline\"",
			"site:ceb.mu/procurement/tender Mauritius tender closing date",
			"site:tenders.go.ke \"Request for Proposal\"",
			"site:sam.gov \"request for proposal\" \"response date\"",
			"site:sam.gov USAID \"response date\"",
			"site:ocds-api.etenders.gov.za/api/OCDSReleases \"Request for Proposal\"",
			"site:nest.go.tz/gateway/nest-data-portal-api/api/releases \"active\" \"tenderPeriod\"",
			"site:gpp.ppda.go.ug/public/bid-invitations tender deadline Uganda",
			"site:umucyo.gov.rw/eb/bav/selectListAdvertisingListForGU.do tender deadline Rwanda",
			"site:ghaneps.gov.gh/epps/quickSearchAction.do current tenders Ghana deadline",
			"site:eprocure.zppa.org.zm/epps/quickSearchAction.do current tenders Zambia deadline",
			"site:maneps.mw/procurement-notice tender closing Malawi deadline",
			"site:nocopo.bpp.gov.ng/Open-Data Nigeria public procurement tender OCID",
			"site:cpbn.com.na/index/external/2 open bids Namibia closing date",
			"site:esppra.co.sz/sppra/tender.php Eswatini tender submission deadline",
			"site:contractsfinder.service.gov.uk tender closing date request for proposal",
			"site:canadabuys.canada.ca \"request for proposal\" closing date",
			"site:tenders.gov.au ATM close date request for tender",
			"site:gets.govt.nz \"Request for Proposal\" deadline",
			"site:usaid.gov \"request for proposals\" deadline",
			"site:grants.gov forecasted opportunity deadline",
			"site:iadb.org procurement \"request for proposals\"",
			"site:data.iadb.org/dataset/project-procurement-bidding-notices-and-notification-of-contract-awards procurement notices",
			"site:spc.int/procurement \"request for proposal\"",
			"site:dai.com/uploads \"request for proposals\" DAI",
			"site:dai.com/uploads \"request for expressions of interest\" DAI",
			"site:rescue.org/rfp RFP procurement",
			"site:rescue.org/procurement-policies-and-bid-opportunities RFP",
			"site:mercycorps.org/tenders tender deadline",
			"site:crs.org/bid-opportunities \"request for proposals\"",
			"site:savethechildren.net/tenders tender deadline",
			"site:plan-international.org/calls-tender tender deadline",
			"site:rti.org/current-opportunities \"Request for Quote/Proposal\" \"Date Proposal Due\"",
			"site:abtglobal.com/doing-business-with-abt/commercial-opportunities \"RFP\" \"Closing\"",
			"site:fhi360.org/partner-us-business-opportunities solicitations \"Closing date\"",
			"site:nrc.no/tender \"Request for Proposal\" \"Deadline for\"",
			"site:nrc.no/tender \"Invitation to tender\" \"Deadline\"",
			"site:nigeria.oxfam.org/procurement-and-consultancy \"Submission Deadline\"",
			"site:thepalladiumgroup.com/tenders RFP tender closing date",
			"site:jhpiego.org/work-with-us \"RFP\" \"Close Date\"",
			"site:dt-global.com/proposals RFP \"Application Deadline\"",
			"site:care.org/about-us/contact-us/request-for-proposals \"Tender submission deadline\"",
			"site:enabel.be/public-procurement \"Closing date\" \"Status :\" \"Open\"",
			"site:enabel.be/grants \"Closing date\" \"Status :\" \"Open\"",
			"site:winrock.org/contracts RFP \"Submission Deadline\"",
			"site:winrock.org/contracts \"download this\" RFP OR EOI OR TOR",
			"site:cowater.com/wp-content/uploads/2026 RFP deadline",
			"site:intdev.tetratech.com.au/partner-with-us tender \"Closing Date and Time\"",
			"site:intdev.tetratecheurope.com/work-with-us/tender-opportunities tender deadline",
			"\"request for proposals\" \"submission deadline\" \"Latin America\"",
			"\"request for proposals\" \"submission deadline\" Caribbean",
			"\"expression of interest\" \"consulting services\" Asia deadline",
			"\"request for proposals\" \"Middle East\" procurement deadline",
			"\"call for proposals\" \"digital transformation\" deadline global",
			"filetype:pdf \"request for proposals\" \"submission deadline\"",
			"filetype:pdf \"terms of reference\" \"proposal\" \"deadline\"",
			"filetype:pdf \"solicitation\" \"proposal due date\"",
			"filetype:pdf \"tender document\" \"closing date\" ICT",
			"filetype:docx \"request for proposals\" procurement",
		]);
		expect(DEFAULT_DISCOVERY_SEARCH_ENGINES).toEqual(["google", "duckduckgo", "bing", "brave"]);
		expect(DEFAULT_DISCOVERY_SOURCE_URLS).toEqual([
			"https://tenders.go.ke/tenders",
			"https://www.ungm.org/Public/Notice",
			"https://www.unops.org/business-opportunities",
			"https://www.iom.int/procurement-opportunities",
			"https://www.who.int/about/accountability/procurement",
			"https://www.ilo.org/about-ilo/procurement",
			"https://www.fao.org/unfao/procurement/en/",
			"https://www.ifad.org/en/corporate-procurement",
			"https://www.unesco.org/en/procurement",
			"https://www.unwomen.org/en/about-us/procurement",
			"https://procurement-notices.undp.org",
			"https://projects.worldbank.org/en/projects-operations/procurement",
			"https://www.afdb.org/en/projects-and-operations/procurement",
			"https://www.adb.org/business/institutional-procurement/notices",
			"https://au.int/en/bids",
			"https://www.aiib.org/en/opportunities/business/project-procurement/list.html",
			"https://www.isdb.org/project-procurement/tenders",
			"https://www.ebrd.com/home/work-with-us/project-procurement/procurement-notices.html",
			"https://www.dgmarket.com",
			"https://www.comesa.int/category/open-tenders/",
			"https://www.un.org/procurement/solicitations-opportunities",
			"https://www.unicef.org/supply/service-contracts-tender-calendar",
			"https://www.caribank.org/work-with-us/procurement/procurement-notices",
			"https://ceb.mu/procurement/tender",
			"https://sam.gov/search/?index=opp&keywords=%22request%20for%20proposal%22",
			"https://sam.gov/search/?index=opp&keywords=USAID",
			"https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/calls-for-proposals?keywords=proposal",
			"https://ocds-api.etenders.gov.za/api/OCDSReleases",
			"https://nest.go.tz/gateway/nest-data-portal-api/api/releases",
			"https://cdn.ppda.go.ug/api/bid-invitations",
			"https://www.umucyo.gov.rw/eb/bav/selectListAdvertisingListForGU.do?menuId=EB01020100&leftTopFlag=l&recordCountPerPage=50",
			"https://www.ghaneps.gov.gh/epps/quickSearchAction.do?searchSelect=6",
			"https://eprocure.zppa.org.zm/epps/quickSearchAction.do?searchSelect=6",
			"https://maneps.mw/rms/api/tender-notices/active-tenders-search",
			"https://nocopo.bpp.gov.ng/Open-Data",
			"https://www.cpbn.com.na/index/external/2",
			"https://esppra.co.sz/sppra/tender.php",
			"https://www.giz.de/en/regions/africa/ghana/tenders",
			"https://www.giz.de/en/regions/africa/south-africa/tenders",
			"https://www.contractsfinder.service.gov.uk/Search",
			"https://canadabuys.canada.ca/en/tender-opportunities",
			"https://www.tenders.gov.au/atm",
			"https://www.gets.govt.nz/ExternalIndex.htm",
			"https://www.grants.gov/search-grants",
			"https://www.usaid.gov/business-forecast",
			"https://www.mercycorps.org/tenders",
			"https://www.crs.org/bid-opportunities",
			"https://www.savethechildren.net/tenders",
			"https://plan-international.org/calls-tender/",
			"https://www.dai.com/our-work/supplier-registration-portal",
			"https://www.rescue.org/procurement-policies-and-bid-opportunities",
			"https://www.gov.uk/government/organisations/foreign-commonwealth-development-office/about/procurement",
			"https://www.fcdoservices.gov.uk/why-choose-us/becoming-a-supplier/",
			"https://www.gtai.de/en/meta/search/kfw-tenders/795748!search",
			"https://www.rti.org/current-opportunities",
			"https://www.abtglobal.com/doing-business-with-abt/commercial-opportunities",
			"https://solicitations.fhi360.org/Solicitation.aspx",
			"https://www.nrc.no/themes/177/tender",
			"https://nigeria.oxfam.org/procurement-and-consultancy",
			"https://thepalladiumgroup.com/tenders",
			"https://jhpiego.org/work-with-us/",
			"https://dt-global.com/proposals/",
			"https://www.care.org/about-us/contact-us/request-for-proposals/",
			"https://www.enabel.be/public-procurement/",
			"https://www.enabel.be/grants/",
			"https://winrock.org/contracts/",
			"https://www.iadb.org/en/how-we-can-work-together/procurement/procurement-projects/procurement-notices",
			"https://data.iadb.org/dataset/project-procurement-bidding-notices-and-notification-of-contract-awards",
			"https://www.iadb.org/en/how-we-can-work-together/procurement/corporate-procurement/corporate-procurement-opportunities",
			"https://www.spc.int/procurement",
			"https://intdev.tetratecheurope.com/work-with-us/tender-opportunities/",
			"https://intdev.tetratech.com.au/partner-with-us/",
		]);
		expect(new Set(DEFAULT_DISCOVERY_QUERIES).size).toBe(DEFAULT_DISCOVERY_QUERIES.length);
		expect(new Set(DEFAULT_DISCOVERY_SOURCE_URLS).size).toBe(DEFAULT_DISCOVERY_SOURCE_URLS.length);
	});

	it("keeps scheduled and legacy discovery inputs on source-document defaults", () => {
		expect(withDefaultDiscoveryRuntimeOptions({})).toMatchObject({
			queries: [...DEFAULT_DISCOVERY_QUERIES],
			engines: [...DEFAULT_DISCOVERY_SEARCH_ENGINES],
			sourceUrls: [...DEFAULT_DISCOVERY_SOURCE_URLS],
			sourceScrapeLimit: 50,
			scrapeTopResults: true,
			scrapeLimit: 5,
			browserFallback: true,
			browserFallbackLimit: 5,
			downloadDiscoveredDocuments: true,
			downloadLimit: 20,
		});

		expect(withDefaultDiscoveryRuntimeOptions({
			query: "ICT tender East Africa",
		})).toMatchObject({
			query: "ICT tender East Africa",
			queries: undefined,
			engines: [...DEFAULT_DISCOVERY_SEARCH_ENGINES],
			sourceUrls: [...DEFAULT_DISCOVERY_SOURCE_URLS],
			sourceScrapeLimit: 50,
			scrapeTopResults: true,
			scrapeLimit: 5,
			browserFallback: true,
			browserFallbackLimit: 5,
			downloadDiscoveredDocuments: true,
			downloadLimit: 20,
		});

		expect(withDefaultDiscoveryRuntimeOptions({
			sourceUrls: ["https://buyer.example/tenders"],
			downloadDiscoveredDocuments: false,
		})).toMatchObject({
			queries: undefined,
			engines: [...DEFAULT_DISCOVERY_SEARCH_ENGINES],
			sourceUrls: ["https://buyer.example/tenders"],
			downloadDiscoveredDocuments: false,
		});
	});
});
