import type { WorkflowTemplateInput } from "@/lib/actions/workflow-runtime";

export const WORKFLOW_TEMPLATE_CATALOG: WorkflowTemplateInput[] = [
	{
		templateKey: "evidence_claim_remediation",
		name: "Evidence Claim Remediation",
		description: "Unsupported or stale proposal claims move through evidence collection, review, waiver, or removal.",
		subjectType: "evidence_claim",
		states: ["detected", "assigned", "evidence_needed", "review", "resolved", "waived", "removed"],
		transitions: [
			{ action: "assign", from: ["detected"], to: "assigned", requiredRoles: ["proposal_manager"] },
			{ action: "request_evidence", from: ["assigned"], to: "evidence_needed", requiredRoles: ["reviewer"] },
			{ action: "submit_evidence", from: ["evidence_needed", "assigned"], to: "review" },
			{ action: "resolve", from: ["review"], to: "resolved", requiredRoles: ["approver"] },
			{ action: "waive", from: ["review", "evidence_needed"], to: "waived", requiredRoles: ["compliance_officer"], requiresReason: true },
			{ action: "remove_claim", from: ["review", "evidence_needed"], to: "removed", requiredRoles: ["writer"], requiresReason: true },
		],
		slaPolicy: { defaultHours: 48, escalationRole: "compliance_lead", priorityHours: { high: 24, critical: 8 } },
		notificationPolicy: { onTransition: ["assigned", "review"], onBreach: ["compliance_lead"], onEscalation: ["proposal_manager"] },
		portalPolicy: { visibleStates: ["assigned", "review"] },
		metadata: { jtbdIds: ["JTBD-029", "JTBD-030", "JTBD-071"], priority: "P1" },
	},
	{
		templateKey: "pricing_approval",
		name: "Pricing Approval",
		description: "Cost elements and final price packages require authority review, sensitivity checks, and lock control.",
		subjectType: "pricing_package",
		states: ["draft", "analyst_review", "authority_review", "locked", "rejected", "reopened", "closed"],
		transitions: [
			{ action: "submit", from: ["draft", "reopened"], to: "analyst_review", requiredRoles: ["pricing_analyst"] },
			{ action: "escalate_authority", from: ["analyst_review"], to: "authority_review", requiredRoles: ["pricing_analyst"] },
			{ action: "lock", from: ["authority_review"], to: "locked", requiredRoles: ["finance_approver"] },
			{ action: "reject", from: ["analyst_review", "authority_review"], to: "rejected", requiredRoles: ["finance_approver"], requiresReason: true },
			{ action: "reopen", from: ["locked", "rejected"], to: "reopened", requiredRoles: ["finance_approver"], requiresReason: true },
			{ action: "close", from: ["locked", "rejected"], to: "closed", requiredRoles: ["finance_approver"] },
		],
		slaPolicy: { defaultHours: 72, escalationRole: "finance_lead", priorityHours: { critical: 12 } },
		notificationPolicy: { onTransition: ["authority_review", "locked", "rejected"], onBreach: ["finance_lead"] },
		metadata: { jtbdIds: ["JTBD-036", "JTBD-037"], priority: "P0" },
	},
	{
		templateKey: "import_sync_governance",
		name: "Import And Sync Governance",
		description: "External imports and connector sync jobs validate mappings, review conflicts, commit changes, and verify rollback.",
		subjectType: "import_sync_job",
		states: ["mapped", "validated", "conflict_review", "approved", "executing", "committed", "rolled_back", "failed"],
		transitions: [
			{ action: "validate", from: ["mapped"], to: "validated" },
			{ action: "flag_conflicts", from: ["validated"], to: "conflict_review" },
			{ action: "approve", from: ["validated", "conflict_review"], to: "approved", requiredRoles: ["operations"] },
			{ action: "execute", from: ["approved"], to: "executing", requiredRoles: ["system"] },
			{ action: "commit", from: ["executing"], to: "committed", requiredRoles: ["system"] },
			{ action: "rollback", from: ["executing", "committed", "failed"], to: "rolled_back", requiredRoles: ["operations"], requiresReason: true },
			{ action: "fail", from: ["executing"], to: "failed", requiredRoles: ["system"], requiresReason: true },
		],
		slaPolicy: { defaultHours: 24, escalationRole: "integration_admin" },
		notificationPolicy: { onTransition: ["conflict_review", "failed", "rolled_back"], onBreach: ["integration_admin"] },
		metadata: { jtbdIds: ["JTBD-053", "JTBD-061", "JTBD-062", "JTBD-074"], priority: "P1" },
	},
	{
		templateKey: "partner_portal_contribution",
		name: "Partner Portal Contribution",
		description: "Partner users receive scoped assignments, submit contributions, and route work through internal review.",
		subjectType: "partner_assignment",
		states: ["invited", "accepted", "assigned", "submitted", "internal_review", "accepted_final", "rejected", "expired"],
		transitions: [
			{ action: "accept_invite", from: ["invited"], to: "accepted" },
			{ action: "assign_scope", from: ["accepted"], to: "assigned", requiredRoles: ["proposal_manager"] },
			{ action: "submit", from: ["assigned"], to: "submitted" },
			{ action: "route_review", from: ["submitted"], to: "internal_review", requiredRoles: ["proposal_manager"] },
			{ action: "accept", from: ["internal_review"], to: "accepted_final", requiredRoles: ["reviewer"] },
			{ action: "reject", from: ["internal_review"], to: "rejected", requiredRoles: ["reviewer"], requiresReason: true },
			{ action: "expire", from: ["invited", "accepted", "assigned"], to: "expired", requiredRoles: ["system"], requiresReason: true },
		],
		slaPolicy: { defaultHours: 96, escalationRole: "partner_manager" },
		notificationPolicy: { onTransition: ["invited", "assigned", "rejected"], onBreach: ["partner_manager"] },
		portalPolicy: { visibleStates: ["invited", "accepted", "assigned", "submitted", "rejected"], portalRole: "partner" },
		metadata: { jtbdIds: ["JTBD-043", "JTBD-044"], priority: "P1" },
	},
	{
		templateKey: "ai_governance_review",
		name: "AI Governance Review",
		description: "AI output, prompt changes, provider routing, and model degradation are reviewed before production use.",
		subjectType: "ai_governance_event",
		states: ["detected", "triage", "eval_required", "human_review", "approved", "rejected", "rolled_back"],
		transitions: [
			{ action: "triage", from: ["detected"], to: "triage", requiredRoles: ["ai_lead"] },
			{ action: "require_eval", from: ["triage"], to: "eval_required", requiredRoles: ["ai_lead"] },
			{ action: "submit_review", from: ["eval_required", "triage"], to: "human_review" },
			{ action: "approve", from: ["human_review"], to: "approved", requiredRoles: ["ai_lead"] },
			{ action: "reject", from: ["human_review"], to: "rejected", requiredRoles: ["ai_lead"], requiresReason: true },
			{ action: "rollback", from: ["approved"], to: "rolled_back", requiredRoles: ["ai_lead"], requiresReason: true },
		],
		slaPolicy: { defaultHours: 72, escalationRole: "ai_lead" },
		notificationPolicy: { onTransition: ["eval_required", "human_review", "rolled_back"], onBreach: ["ai_lead"] },
		metadata: { jtbdIds: ["JTBD-023", "JTBD-024", "JTBD-055", "JTBD-069"], priority: "P2" },
	},
	{
		templateKey: "reporting_audit_package",
		name: "Reporting And Audit Package",
		description: "Compliance, quality, and dashboard reports are snapshot, reviewed, approved, and retained.",
		subjectType: "audit_report_package",
		states: ["draft", "snapshot_ready", "review", "approved", "published", "rejected", "retained"],
		transitions: [
			{ action: "snapshot", from: ["draft"], to: "snapshot_ready", requiredRoles: ["system"] },
			{ action: "submit_review", from: ["snapshot_ready"], to: "review", requiredRoles: ["auditor"] },
			{ action: "approve", from: ["review"], to: "approved", requiredRoles: ["approver"] },
			{ action: "publish", from: ["approved"], to: "published", requiredRoles: ["auditor"] },
			{ action: "reject", from: ["review"], to: "rejected", requiredRoles: ["approver"], requiresReason: true },
			{ action: "retain", from: ["published"], to: "retained", requiredRoles: ["system"] },
		],
		slaPolicy: { defaultHours: 48, escalationRole: "audit_lead" },
		notificationPolicy: { onTransition: ["review", "approved", "published"], onBreach: ["audit_lead"] },
		metadata: { jtbdIds: ["JTBD-017", "JTBD-063", "JTBD-070"], priority: "P1" },
	},
	{
		templateKey: "mobile_offline_sync",
		name: "Mobile Offline Sync",
		description: "Offline workflow actions are queued, reconciled, conflict-checked, and audited when connectivity returns.",
		subjectType: "offline_action_batch",
		states: ["cached", "syncing", "conflict_review", "merged", "rejected", "superseded"],
		transitions: [
			{ action: "sync", from: ["cached"], to: "syncing" },
			{ action: "flag_conflict", from: ["syncing"], to: "conflict_review" },
			{ action: "merge", from: ["syncing", "conflict_review"], to: "merged", requiredRoles: ["system"] },
			{ action: "reject", from: ["conflict_review"], to: "rejected", requiredRoles: ["operations"], requiresReason: true },
			{ action: "supersede", from: ["cached", "syncing"], to: "superseded", requiredRoles: ["system"], requiresReason: true },
		],
		slaPolicy: { defaultHours: 12, escalationRole: "operations" },
		notificationPolicy: { onTransition: ["conflict_review", "rejected"], onBreach: ["operations"] },
		portalPolicy: { visibleStates: ["cached", "conflict_review", "merged", "rejected"] },
		metadata: { jtbdIds: ["JTBD-067"], priority: "Strategic" },
	},
];
