/**
 * HDSI AI Submodule
 *
 * AI generation, streaming, embeddings, RAG, domain models,
 * predictive generation, style enforcement, diagrams, coherence,
 * and diff preview.
 *
 * Dependency graph:
 *   ai-client       -> core/types
 *   ai-generation   -> core/types
 *   domain-models   -> core/types
 *   predictive      -> core/types, domain-models
 *   streaming       -> (none)
 *   embeddings      -> core/types
 *   rag             -> embeddings, core/types
 *   coherence       -> embeddings, core/types
 *   style-guide     -> (none)
 *   diagrams        -> (none)
 *   ai-diff-preview -> (none)
 */

// Multi-model AI generation (Azure OpenAI, OpenAI, Anthropic, local)
export {
  generateNodeContent,
  generateBatch,
  generateNodeStreaming,
  generateOutlineFromTemplate,
  createGenerationQueue,
  DEFAULT_CONFIGS,
} from "../ai-generation";

// Streaming token generation
export {
  streamGeneration,
  simulateStreamingGeneration,
  useStreamingGeneration,
  useTokenVisualization,
} from "../streaming";

// Vector embeddings and semantic search
export {
  generateEmbedding,
  generateEmbeddingsForNodes,
  cosineSimilarity,
  findSimilarNodes,
  semanticSearch,
  clusterEmbeddings,
  useEmbeddings,
} from "../embeddings";

// RAG context assembly pipeline
export {
  assembleRAGContext,
  optimizeContext,
  validateCoherence,
  useRAG,
} from "../rag";

// Fine-tuned domain models (FAR/DFARS, technical specs, academic)
export {
  DOMAIN_ADAPTERS,
  detectDomain,
  detectDomainForNode,
  detectDomainForDocument,
  generateWithDomainAdapter,
  generateWithOptimalDomain,
  useDomainDetection,
  useDomainGeneration,
} from "../domain-models";

// Predictive (speculative) content generation
export {
  predictiveGenerator,
  usePredictiveGeneration,
} from "../predictive";

// Style guide enforcement engine
export {
  STYLE_PRESETS,
  analyzeStyle,
  useStyleGuide,
  useRealtimeStyleGuide,
} from "../style-guide";

// Visual diagram generation (Mermaid, DALL-E, SVG)
export {
  generateMermaidDiagram,
  generateDalleDiagram,
  generateSvgDiagram,
  autoGenerateDiagram,
  useDiagramGeneration,
  generateDiagramsForDocument,
} from "../diagrams";

// AI diff preview (Cursor-style edit review)
export {
  useAIDiffPreview,
  generateDiff,
  assemblePreviewText,
  assembleFinalText,
  estimateReadingImpact,
  generateChangeExplanation,
  type TextChange,
  type ChangeType,
  type DiffResult,
  type PreviewSession,
  type GranularityOptions,
} from "../ai-diff-preview";
