"""
African Procurement Sources Registry

Comprehensive registry of procurement sources across all 58 African
ISO-2 territories. Includes multilateral regional portals, national
tender portals, and fallback entries for every country/sub-region.
"""

from typing import List, Dict, Any

AFRICAN_COUNTRY_CODES: list[tuple[str, str]] = [
	("DZ", "Algeria"), ("AO", "Angola"), ("BJ", "Benin"), ("BW", "Botswana"),
	("BF", "Burkina Faso"), ("BI", "Burundi"), ("CV", "Cabo Verde"), ("CM", "Cameroon"),
	("CF", "Central African Republic"), ("TD", "Chad"), ("KM", "Comoros"), ("CG", "Congo"),
	("CD", "Democratic Republic of the Congo"), ("CI", "Cote d'Ivoire"), ("DJ", "Djibouti"),
	("EG", "Egypt"), ("GQ", "Equatorial Guinea"), ("ER", "Eritrea"), ("SZ", "Eswatini"),
	("ET", "Ethiopia"), ("GA", "Gabon"), ("GM", "Gambia"), ("GH", "Ghana"),
	("GN", "Guinea"), ("GW", "Guinea-Bissau"), ("KE", "Kenya"), ("LS", "Lesotho"),
	("LR", "Liberia"), ("LY", "Libya"), ("MG", "Madagascar"), ("MW", "Malawi"),
	("ML", "Mali"), ("MR", "Mauritania"), ("MU", "Mauritius"), ("MA", "Morocco"),
	("MZ", "Mozambique"), ("NA", "Namibia"), ("NE", "Niger"), ("NG", "Nigeria"),
	("RW", "Rwanda"), ("ST", "Sao Tome and Principe"), ("SN", "Senegal"), ("SC", "Seychelles"),
	("SL", "Sierra Leone"), ("SO", "Somalia"), ("ZA", "South Africa"), ("SS", "South Sudan"),
	("SD", "Sudan"), ("TZ", "Tanzania"), ("TG", "Togo"), ("TN", "Tunisia"),
	("UG", "Uganda"), ("ZM", "Zambia"), ("ZW", "Zimbabwe"),
	("EH", "Western Sahara"), ("RE", "Reunion"), ("YT", "Mayotte"), ("SH", "Saint Helena"),
]


def get_regional_sources() -> List[Dict[str, Any]]:
	"""Return multilateral/regional procurement portals serving Africa."""
	return [
		{
			"name": "African Development Bank (AfDB) Procurement",
			"url": "https://www.afdb.org/en/projects-and-operations/procurement",
			"country": "ML",
			"region": "Pan-African",
			"source_type": "government_international",
			"geographic_scope": "continental",
			"typical_opportunities_per_day": 5,
			"opportunity_types": ["International Tenders", "Consultancies", "Grants"],
			"value_ranges": ["$100K+", "$1M+", "$10M+"],
			"recommended_scraper": "universal",
			"language": "en",
		},
		{
			"name": "ECOWAS Procurement Notice Board",
			"url": "https://ecowap.ecowas.int/",
			"country": "NG",
			"region": "West Africa",
			"source_type": "government_international",
			"geographic_scope": "regional",
			"typical_opportunities_per_day": 2,
			"opportunity_types": ["Regional Tenders", "Consultancies"],
			"recommended_scraper": "universal",
			"language": "en",
		},
		{
			"name": "SADC Procurement Portal",
			"url": "https://www.sadc.int/",
			"country": "ZA",
			"region": "Southern Africa",
			"source_type": "government_international",
			"geographic_scope": "regional",
			"typical_opportunities_per_day": 2,
			"opportunity_types": ["Regional Tenders"],
			"recommended_scraper": "universal",
			"language": "en",
		},
		{
			"name": "East African Community (EAC) Procurement",
			"url": "https://www.eac.int/",
			"country": "TZ",
			"region": "East Africa",
			"source_type": "government_international",
			"geographic_scope": "regional",
			"typical_opportunities_per_day": 2,
			"opportunity_types": ["Regional Tenders"],
			"recommended_scraper": "universal",
			"language": "en",
		},
		{
			"name": "COMESA Business Council Tenders",
			"url": "https://www.comesa.int/",
			"country": "ZM",
			"region": "Eastern/Southern Africa",
			"source_type": "government_international",
			"geographic_scope": "regional",
			"typical_opportunities_per_day": 2,
			"opportunity_types": ["Regional Tenders"],
			"recommended_scraper": "universal",
			"language": "en",
		},
		{
			"name": "UNDP Africa Procurement",
			"url": "https://procurement-notices.undp.org/",
			"country": "ZA",
			"region": "Pan-African",
			"source_type": "ngo_international",
			"geographic_scope": "continental",
			"typical_opportunities_per_day": 10,
			"opportunity_types": ["UN Tenders", "Consultancies", "Grants"],
			"value_ranges": ["$50K+", "$500K+"],
			"recommended_scraper": "universal",
			"language": "en",
		},
		{
			"name": "World Bank Africa Tenders",
			"url": "https://www.worldbank.org/en/projects-operations/procurement",
			"country": "ZA",
			"region": "Pan-African",
			"source_type": "government_international",
			"geographic_scope": "continental",
			"typical_opportunities_per_day": 8,
			"opportunity_types": ["International Tenders", "Consultancies"],
			"value_ranges": ["$100K+", "$1M+"],
			"recommended_scraper": "universal",
			"language": "en",
		},
		{
			"name": "IGAD Procurement (Horn of Africa)",
			"url": "https://igad.int/procurement/",
			"country": "DJ",
			"region": "Horn of Africa",
			"source_type": "government_international",
			"geographic_scope": "regional",
			"typical_opportunities_per_day": 1,
			"opportunity_types": ["Regional Tenders"],
			"recommended_scraper": "universal",
			"language": "en",
		},
		{
			"name": "CEMAC Procurement (Central Africa)",
			"url": "https://www.cemac.int/",
			"country": "CM",
			"region": "Central Africa",
			"source_type": "government_international",
			"geographic_scope": "regional",
			"typical_opportunities_per_day": 1,
			"opportunity_types": ["Regional Tenders"],
			"recommended_scraper": "universal",
			"language": "fr",
		},
	]


def get_national_sources() -> List[Dict[str, Any]]:
	"""Return known national procurement portals for all 54 African countries."""
	return [
		# ── North Africa ───────────────────────────────────────────────────────
		{
			"name": "Algeria Public Procurement (ARMP)",
			"url": "https://www.marchespublics.gov.dz/",
			"country": "DZ", "region": "North Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 30, "language": "ar",
			"recommended_scraper": "universal",
		},
		{
			"name": "Egypt Government Tenders Portal",
			"url": "https://www.tenders.gov.eg/",
			"country": "EG", "region": "North Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 50, "language": "ar",
			"recommended_scraper": "universal",
		},
		{
			"name": "Libya Public Procurement",
			"url": "https://www.tenders.gov.ly/",
			"country": "LY", "region": "North Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 10, "language": "ar",
			"recommended_scraper": "universal",
		},
		{
			"name": "Morocco Public Procurement Portal",
			"url": "https://www.marchespublics.gov.ma/",
			"country": "MA", "region": "North Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 40, "language": "ar",
			"recommended_scraper": "universal",
		},
		{
			"name": "Sudan National Procurement Commission",
			"url": "https://www.npc.gov.sd/",
			"country": "SD", "region": "North Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 10, "language": "ar",
			"recommended_scraper": "universal",
		},
		{
			"name": "Tunisia Public Procurement (ARMP)",
			"url": "https://www.marchespublics.gov.tn/",
			"country": "TN", "region": "North Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 30, "language": "ar",
			"recommended_scraper": "universal",
		},

		# ── West Africa ────────────────────────────────────────────────────────
		{
			"name": "Benin Public Procurement (ARMP)",
			"url": "https://www.armp.bj/",
			"country": "BJ", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 10, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Burkina Faso Directorate of Public Procurement",
			"url": "https://www.dgmp.gov.bf/",
			"country": "BF", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 10, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Cabo Verde Public Procurement",
			"url": "https://contratacaopublica.gov.cv/",
			"country": "CV", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "pt",
			"recommended_scraper": "universal",
		},
		{
			"name": "Cote d'Ivoire Public Procurement (ARMP)",
			"url": "https://www.armp.ci/",
			"country": "CI", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 20, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Gambia Government Public Procurement Authority",
			"url": "https://www.gppa.gm/",
			"country": "GM", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 5, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Ghana Public Procurement Authority",
			"url": "https://www.ppaghana.org/",
			"country": "GH", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 25, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Guinea Public Procurement (ARMP)",
			"url": "https://www.marches-publics.gov.gn/",
			"country": "GN", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Guinea-Bissau Ministry of Finance Tenders",
			"url": "https://www.mf.gov.gw/",
			"country": "GW", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "pt",
			"recommended_scraper": "universal",
			"notes": "No dedicated procurement portal; tenders published via Ministry of Finance",
		},
		{
			"name": "Liberia Public Procurement and Concessions Commission",
			"url": "https://www.ppcc.gov.lr/",
			"country": "LR", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Mali Public Procurement (ARMDS)",
			"url": "https://www.armds.gov.ml/",
			"country": "ML", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 12, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Mauritania Public Procurement (ARMP)",
			"url": "https://www.armp.mr/",
			"country": "MR", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "ar",
			"recommended_scraper": "universal",
		},
		{
			"name": "Niger Public Procurement Authority (ARMP)",
			"url": "https://www.armp.ne/",
			"country": "NE", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Nigeria Bureau of Public Procurement (BPP)",
			"url": "https://www.bpp.gov.ng/",
			"country": "NG", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 40, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Senegal Public Procurement (DGMP)",
			"url": "https://www.marchespublics.sn/",
			"country": "SN", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 15, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Sierra Leone National Public Procurement Authority",
			"url": "https://www.nppa.gov.sl/",
			"country": "SL", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Togo Public Procurement Authority (ARMP)",
			"url": "https://www.armp.tg/",
			"country": "TG", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "fr",
			"recommended_scraper": "universal",
		},

		# ── Central Africa ─────────────────────────────────────────────────────
		{
			"name": "Cameroon Public Procurement (ARMP)",
			"url": "https://www.marchespublics.cm/",
			"country": "CM", "region": "Central Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 15, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "CAR Ministry of Finance Tenders",
			"url": "https://www.finances.gouv.cf/",
			"country": "CF", "region": "Central Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "fr",
			"recommended_scraper": "universal",
			"notes": "No dedicated procurement portal; tenders published via Ministry of Finance",
		},
		{
			"name": "Chad Directorate of Public Procurement",
			"url": "https://www.dgmp.td/",
			"country": "TD", "region": "Central Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 5, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Republic of Congo Public Procurement",
			"url": "https://www.marches-publics.cg/",
			"country": "CG", "region": "Central Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 6, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "DRC Public Procurement Authority (ACMP)",
			"url": "https://acmp.gouv.cd/",
			"country": "CD", "region": "Central Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 15, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Equatorial Guinea Ministry of Finance Tenders",
			"url": "https://www.minhap.gov.gq/",
			"country": "GQ", "region": "Central Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "es",
			"recommended_scraper": "universal",
			"notes": "No dedicated procurement portal; tenders via Ministry of Finance",
		},
		{
			"name": "Gabon Directorate of Public Procurement",
			"url": "https://dgmp.gouv.ga/",
			"country": "GA", "region": "Central Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Sao Tome & Principe Government Tenders",
			"url": "https://www.gov.st/",
			"country": "ST", "region": "Central Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "pt",
			"recommended_scraper": "universal",
			"notes": "Very small island state; tenders via general government portal",
		},

		# ── East Africa ────────────────────────────────────────────────────────
		{
			"name": "Burundi Public Procurement (ARMP)",
			"url": "https://www.armp.bi/",
			"country": "BI", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 5, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Comoros Government Tenders",
			"url": "https://www.beit-salam.km/",
			"country": "KM", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "fr",
			"recommended_scraper": "universal",
			"notes": "Very small island state; tenders via presidency portal",
		},
		{
			"name": "Djibouti Public Procurement",
			"url": "https://www.presidence.dj/appels-offres.php",
			"country": "DJ", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Eritrea Ministry of Finance Tenders",
			"url": "https://www.mof.gov.er/",
			"country": "ER", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "ti",
			"recommended_scraper": "universal",
			"notes": "Severely restricted internet; minimal online procurement presence",
		},
		{
			"name": "Ethiopia Public Procurement Agency",
			"url": "https://www.ppa.gov.et/",
			"country": "ET", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 20, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Kenya Public Procurement Regulatory Authority",
			"url": "https://www.ppra.go.ke/",
			"country": "KE", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 30, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Madagascar Public Procurement Authority (ARMP)",
			"url": "https://www.armp.gov.mg/",
			"country": "MG", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Mauritius Public Procurement",
			"url": "https://www.publicprocurement.govmu.org/",
			"country": "MU", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 5, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Rwanda Public Procurement Authority (RPPA)",
			"url": "https://www.rppa.gov.rw/",
			"country": "RW", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 10, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Seychelles Public Procurement",
			"url": "https://www.publicprocurement.gov.sc/",
			"country": "SC", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Somalia Ministry of Finance Tenders",
			"url": "https://www.mof.gov.so/",
			"country": "SO", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "so",
			"recommended_scraper": "universal",
			"notes": "Fragile state; procurement via Ministry of Finance and donor portals",
		},
		{
			"name": "South Sudan Public Procurement",
			"url": "https://grss-mof.org/public-procurement/",
			"country": "SS", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "en",
			"recommended_scraper": "universal",
			"notes": "Young state; procurement via Ministry of Finance portal",
		},
		{
			"name": "Tanzania Public Procurement Regulatory Authority",
			"url": "https://www.ppra.go.tz/",
			"country": "TZ", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 20, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Uganda Public Procurement and Disposal Authority",
			"url": "https://www.ppda.go.ug/",
			"country": "UG", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 20, "language": "en",
			"recommended_scraper": "universal",
		},

		# ── Southern Africa ────────────────────────────────────────────────────
		{
			"name": "Angola Public Procurement Portal",
			"url": "https://www.portaldecompras.org/",
			"country": "AO", "region": "Southern Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 15, "language": "pt",
			"recommended_scraper": "universal",
		},
		{
			"name": "Botswana Public Procurement (PPADB)",
			"url": "https://www.ppadb.co.bw/",
			"country": "BW", "region": "Southern Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Eswatini Public Procurement",
			"url": "https://www.gov.sz/index.php/procurement",
			"country": "SZ", "region": "Southern Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 4, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Lesotho Public Procurement Directorate",
			"url": "https://www.ppd.org.ls/",
			"country": "LS", "region": "Southern Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 5, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Malawi Public Procurement and Disposal Authority",
			"url": "https://www.ppda.mw/",
			"country": "MW", "region": "Southern Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Mozambique National Procurement Commission (CNPMP)",
			"url": "https://www.cnpmap.gov.mz/",
			"country": "MZ", "region": "Southern Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 12, "language": "pt",
			"recommended_scraper": "universal",
		},
		{
			"name": "Namibia Central Procurement Board (CPB)",
			"url": "https://www.cpb.gov.na/",
			"country": "NA", "region": "Southern Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "South Africa National Treasury eTender Portal",
			"url": "https://www.etenders.gov.za/",
			"country": "ZA", "region": "Southern Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 80, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Zambia Public Procurement Authority (ZPPA)",
			"url": "https://www.zppa.org.zm/",
			"country": "ZM", "region": "Southern Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 12, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Zimbabwe Procurement Regulatory Authority (ZPPA)",
			"url": "https://www.zppa.co.zw/",
			"country": "ZW", "region": "Southern Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 10, "language": "en",
			"recommended_scraper": "universal",
		},

		# ── Territories ────────────────────────────────────────────────────────
		{
			"name": "Reunion Public Procurement (BOAMP/DECP)",
			"url": "https://www.boamp.fr/",
			"country": "RE", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "regional",
			"typical_opportunities_per_day": 5, "language": "fr",
			"recommended_scraper": "universal",
			"notes": "French overseas territory; uses French national procurement system",
		},
		{
			"name": "Mayotte Public Procurement (BOAMP)",
			"url": "https://www.boamp.fr/",
			"country": "YT", "region": "East Africa",
			"source_type": "government_federal", "geographic_scope": "regional",
			"typical_opportunities_per_day": 2, "language": "fr",
			"recommended_scraper": "universal",
			"notes": "French overseas department; uses French national procurement system",
		},
		{
			"name": "Saint Helena Government Tenders",
			"url": "https://www.sainthelena.gov.sh/government/tenders/",
			"country": "SH", "region": "West Africa",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "en",
			"recommended_scraper": "universal",
			"notes": "British Overseas Territory",
		},
	]


def get_country_fallbacks() -> List[Dict[str, Any]]:
	"""Return minimal fallback entries for countries not in get_national_sources().

	After the full national-sources expansion, only Western Sahara (disputed
	territory, no government portal) requires a placeholder.
	"""
	known = {s["country"] for s in get_national_sources()}
	region_map = {
		"DZ": "North Africa", "AO": "Southern Africa", "BJ": "West Africa", "BW": "Southern Africa",
		"BF": "West Africa", "BI": "East Africa", "CV": "West Africa", "CM": "Central Africa",
		"CF": "Central Africa", "TD": "Central Africa", "KM": "East Africa", "CG": "Central Africa",
		"CD": "Central Africa", "CI": "West Africa", "DJ": "East Africa", "EG": "North Africa",
		"GQ": "Central Africa", "ER": "East Africa", "SZ": "Southern Africa", "ET": "East Africa",
		"GA": "Central Africa", "GM": "West Africa", "GN": "West Africa", "GW": "West Africa",
		"KE": "East Africa", "LS": "Southern Africa", "LR": "West Africa", "LY": "North Africa",
		"MG": "East Africa", "MW": "Southern Africa", "ML": "West Africa", "MR": "West Africa",
		"MU": "East Africa", "MA": "North Africa", "MZ": "Southern Africa", "NA": "Southern Africa",
		"NE": "West Africa", "NG": "West Africa", "RW": "East Africa", "ST": "Central Africa",
		"SN": "West Africa", "SC": "East Africa", "SL": "West Africa", "SO": "East Africa",
		"ZA": "Southern Africa", "SS": "East Africa", "SD": "North Africa", "TZ": "East Africa",
		"TG": "West Africa", "TN": "North Africa", "UG": "East Africa", "ZM": "Southern Africa",
		"ZW": "Southern Africa", "EH": "North Africa", "RE": "East Africa", "YT": "East Africa",
		"SH": "West Africa",
	}
	fallbacks = []
	for code, name in AFRICAN_COUNTRY_CODES:
		if code in known:
			continue
		fallbacks.append({
			"name": f"{name} Procurement (Placeholder)",
			"url": "https://example.com/placeholder",
			"country": code,
			"region": region_map.get(code, "Africa"),
			"source_type": "government_federal",
			"geographic_scope": "national",
			"typical_opportunities_per_day": 0,
			"status": "placeholder",
			"notes": f"Dedicated portal for {name} not yet catalogued",
		})
	return fallbacks
