"""
African Expanded Sources — Sub-national, Parastatals, Programs, and Sector Bodies

Doubles African coverage by adding:
1. Sub-national procurement portals (Nigeria states, South African provinces/metros,
   Kenya counties, Ethiopian regions, Egyptian governorates)
2. African parastatal companies and state-owned enterprises
3. African infrastructure, energy, and utility programs
4. African health sector institutions
5. Donor-funded Africa programs with own procurement portals
6. African financial institutions and sector bodies
"""

from typing import Any


def get_nigeria_state_portals() -> list[dict[str, Any]]:
	"""State-level procurement portals for Nigeria's most active states."""
	return [
		{"name": "Lagos State Procurement Agency (LSPPA)", "url": "https://lagosprocurement.gov.ng/",
		 "country": "NG", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 20,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Rivers State Government Tenders", "url": "https://www.rivers.gov.ng/",
		 "country": "NG", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 10,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Kaduna State Government Procurement", "url": "https://kdsg.gov.ng/",
		 "country": "NG", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 8,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Kano State Government Tenders", "url": "https://www.kanostate.gov.ng/",
		 "country": "NG", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 8,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Abuja FCT Administration Procurement", "url": "https://www.fct.gov.ng/",
		 "country": "NG", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 12,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Delta State Government Tenders", "url": "https://www.deltastate.gov.ng/",
		 "country": "NG", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 8,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Ogun State Government Procurement", "url": "https://www.ogunstate.gov.ng/",
		 "country": "NG", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 6,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Anambra State Government Tenders", "url": "https://www.anambra.gov.ng/",
		 "country": "NG", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 6,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Enugu State Government Procurement", "url": "https://www.enugu.gov.ng/",
		 "country": "NG", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Cross River State Government Tenders", "url": "https://www.crossriverstate.gov.ng/",
		 "country": "NG", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Akwa Ibom State Government Procurement", "url": "https://www.akwaibomstate.gov.ng/",
		 "country": "NG", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 8,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Bayelsa State Government Tenders", "url": "https://www.bayelsastate.gov.ng/",
		 "country": "NG", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal"},
	]


def get_south_africa_sub_national() -> list[dict[str, Any]]:
	"""South African provincial and metro municipality procurement portals."""
	return [
		{"name": "Gauteng Provincial Government Tenders", "url": "https://www.gpg.gov.za/",
		 "country": "ZA", "region": "Southern Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 20,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Western Cape Government Tenders", "url": "https://www.westerncape.gov.za/tenders",
		 "country": "ZA", "region": "Southern Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 15,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "KwaZulu-Natal Provincial Tenders", "url": "https://www.kzngov.gov.za/",
		 "country": "ZA", "region": "Southern Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 15,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Eastern Cape Provincial Tenders", "url": "https://www.ecprov.gov.za/",
		 "country": "ZA", "region": "Southern Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 10,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Limpopo Province Procurement", "url": "https://www.limpopo.gov.za/",
		 "country": "ZA", "region": "Southern Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 8,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "City of Johannesburg Tenders", "url": "https://www.joburg.org.za/",
		 "country": "ZA", "region": "Southern Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 15,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "City of Cape Town eTenders", "url": "https://www.capetown.gov.za/",
		 "country": "ZA", "region": "Southern Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 15,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "eThekwini Municipality Tenders (Durban)", "url": "https://www.ethekwini.gov.za/",
		 "country": "ZA", "region": "Southern Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 12,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "City of Tshwane Procurement", "url": "https://www.tshwane.gov.za/",
		 "country": "ZA", "region": "Southern Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 12,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Ekurhuleni Metro Municipality Tenders", "url": "https://www.ekurhuleni.gov.za/",
		 "country": "ZA", "region": "Southern Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 8,
		 "language": "en", "recommended_scraper": "universal"},
	]


def get_kenya_county_portals() -> list[dict[str, Any]]:
	"""Kenya county government procurement portals."""
	return [
		{"name": "Nairobi City County Procurement", "url": "https://www.nairobi.go.ke/",
		 "country": "KE", "region": "East Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 8,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Mombasa County Tenders", "url": "https://www.mombasa.go.ke/",
		 "country": "KE", "region": "East Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Kisumu County Procurement", "url": "https://www.kisumu.go.ke/",
		 "country": "KE", "region": "East Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 4,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Nakuru County Tenders", "url": "https://www.nakuru.go.ke/",
		 "country": "KE", "region": "East Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 4,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Kiambu County Procurement", "url": "https://www.kiambu.go.ke/",
		 "country": "KE", "region": "East Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 4,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Kenya Tenders Portal (kenyatenders.go.ke)", "url": "https://www.tenders.go.ke/",
		 "country": "KE", "region": "East Africa", "source_type": "government_federal",
		 "geographic_scope": "national", "typical_opportunities_per_day": 30,
		 "language": "en", "recommended_scraper": "universal",
		 "notes": "National aggregator for all county and national tenders"},
	]


def get_african_parastatals() -> list[dict[str, Any]]:
	"""African state-owned enterprises and parastatal companies that regularly tender."""
	return [
		# ── Energy & Utilities ────────────────────────────────────────────────
		{"name": "Eskom (South Africa) Supplier Portal", "url": "https://www.eskom.co.za/suppliers/",
		 "country": "ZA", "region": "Southern Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 10,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "TANESCO (Tanzania Electric Supply) Tenders", "url": "https://www.tanesco.co.tz/",
		 "country": "TZ", "region": "East Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "KENGEN (Kenya Electricity Generating) Tenders", "url": "https://www.kengen.co.ke/",
		 "country": "KE", "region": "East Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 4,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Kenya Power (KPLC) Procurement", "url": "https://www.kplc.co.ke/",
		 "country": "KE", "region": "East Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "ECG Ghana (Electricity Company) Tenders", "url": "https://www.ecgghana.com/",
		 "country": "GH", "region": "West Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 4,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "ZESCO (Zambia Electricity) Procurement", "url": "https://www.zesco.co.zm/",
		 "country": "ZM", "region": "Southern Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 4,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "ZESA Holdings (Zimbabwe) Tenders", "url": "https://www.zesa.co.zw/",
		 "country": "ZW", "region": "Southern Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 3,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "SONABEL (Burkina Faso Electricity) Tenders", "url": "https://www.sonabel.bf/",
		 "country": "BF", "region": "West Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 3,
		 "language": "fr", "recommended_scraper": "universal"},
		{"name": "STEG (Tunisia Electricity and Gas) Procurement", "url": "https://www.steg.com.tn/",
		 "country": "TN", "region": "North Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 5,
		 "language": "ar", "recommended_scraper": "universal"},
		{"name": "ONEE (Morocco Electricity and Water) Tenders", "url": "https://www.one.org.ma/",
		 "country": "MA", "region": "North Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 8,
		 "language": "fr", "recommended_scraper": "universal"},
		# ── Oil & Gas ─────────────────────────────────────────────────────────
		{"name": "NNPC (Nigeria National Petroleum Corp) Tenders", "url": "https://www.nnpcgroup.com/",
		 "country": "NG", "region": "West Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 8,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Sonangol (Angola) Procurement", "url": "https://www.sonangol.co.ao/",
		 "country": "AO", "region": "Southern Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 6,
		 "language": "pt", "recommended_scraper": "universal"},
		{"name": "SONATRACH (Algeria) Tenders", "url": "https://www.sonatrach.com/",
		 "country": "DZ", "region": "North Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 8,
		 "language": "ar", "recommended_scraper": "universal"},
		{"name": "NOCL (Libya National Oil Corporation)", "url": "https://www.noclibya.com.ly/",
		 "country": "LY", "region": "North Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 4,
		 "language": "ar", "recommended_scraper": "universal"},
		# ── Telecoms ──────────────────────────────────────────────────────────
		{"name": "Safaricom Procurement (Kenya)", "url": "https://www.safaricom.co.ke/about/suppliers",
		 "country": "KE", "region": "East Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 3,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "MTN Group Procurement (Pan-Africa)", "url": "https://www.mtn.com/supplier-portal/",
		 "country": "ZA", "region": "Pan-African", "source_type": "corporate",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal"},
		# ── Transport ─────────────────────────────────────────────────────────
		{"name": "Ethiopian Airlines Procurement", "url": "https://www.ethiopianairlines.com/",
		 "country": "ET", "region": "East Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 3,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Transnet (South Africa) Supplier Portal", "url": "https://www.transnet.net/",
		 "country": "ZA", "region": "Southern Africa", "source_type": "corporate",
		 "geographic_scope": "national", "typical_opportunities_per_day": 8,
		 "language": "en", "recommended_scraper": "universal"},
	]


def get_african_health_institutions() -> list[dict[str, Any]]:
	"""African health sector institutions, programs, and health procurement bodies."""
	return [
		{"name": "Africa CDC (Centres for Disease Control) Procurement",
		 "url": "https://africacdc.org/procurement/",
		 "country": "ET", "region": "Pan-African", "source_type": "government_international",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 3,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["health", "cdc", "au"]},
		{"name": "AMREF Health Africa Tenders", "url": "https://amref.org/about/procurement/",
		 "country": "KE", "region": "Pan-African", "source_type": "nonprofit",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 4,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["health", "africa"]},
		{"name": "Global Fund Africa Grants", "url": "https://www.theglobalfund.org/en/applying/",
		 "country": "CH", "region": "Pan-African", "source_type": "foundation",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 3,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["health", "hiv", "malaria", "tb"]},
		{"name": "GAVI Alliance Africa Programmes", "url": "https://www.gavi.org/investing-gavi/apply-funding",
		 "country": "CH", "region": "Pan-African", "source_type": "foundation",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["health", "vaccines"]},
		{"name": "PEPFAR DREAMS/USAID Africa Health Procurement",
		 "url": "https://www.pepfar.gov/partnerships/",
		 "country": "US", "region": "Pan-African", "source_type": "government_federal",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["health", "hiv", "pepfar"]},
		{"name": "CHAI (Clinton Health Access Initiative) Africa",
		 "url": "https://www.clintonhealthaccess.org/about/procurement/",
		 "country": "US", "region": "Pan-African", "source_type": "nonprofit",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 3,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["health", "hiv", "malaria"]},
		{"name": "Africa Health Markets (APHM) Procurement",
		 "url": "https://www.psionline.org/",
		 "country": "US", "region": "Pan-African", "source_type": "nonprofit",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 3,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["health", "family-planning"]},
	]


def get_african_infrastructure_programs() -> list[dict[str, Any]]:
	"""African infrastructure programs, funds, and project preparation facilities."""
	return [
		{"name": "PIDA (Programme for Infrastructure Development in Africa)",
		 "url": "https://www.au-pida.org/",
		 "country": "ET", "region": "Pan-African", "source_type": "government_international",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["infrastructure", "au", "transport", "energy"]},
		{"name": "Africa50 Infrastructure Fund Procurement",
		 "url": "https://www.africa50.com/",
		 "country": "MA", "region": "Pan-African", "source_type": "government_international",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["infrastructure", "investment"]},
		{"name": "NEPAD Infrastructure Project Preparation Facility (NEPAD-IPPF)",
		 "url": "https://www.afdb.org/en/topics-and-sectors/initiatives-partnerships/nepad-ippf",
		 "country": "ET", "region": "Pan-African", "source_type": "government_international",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["infrastructure", "nepad"]},
		{"name": "African Water Facility (AfDB) Procurement",
		 "url": "https://www.africanwaterfacility.org/",
		 "country": "CI", "region": "Pan-African", "source_type": "government_international",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["water", "sanitation", "afdb"]},
		{"name": "SREP (Scaling Up Renewable Energy) Africa",
		 "url": "https://www.climateinvestmentfunds.org/",
		 "country": "US", "region": "Pan-African", "source_type": "government_international",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["energy", "renewable", "climate"]},
		{"name": "GEAPP (Global Energy Alliance for People and Planet) Africa",
		 "url": "https://energyalliance.org/",
		 "country": "US", "region": "Pan-African", "source_type": "foundation",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["energy", "access", "africa"]},
	]


def get_african_donor_programs() -> list[dict[str, Any]]:
	"""Donor-funded programs operating in Africa with own procurement portals."""
	return [
		{"name": "USAID West Africa Regional Mission", "url": "https://www.usaid.gov/west-africa-regional",
		 "country": "GH", "region": "West Africa", "source_type": "government_federal",
		 "geographic_scope": "regional", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["usaid", "west-africa"]},
		{"name": "USAID East Africa Regional Mission", "url": "https://www.usaid.gov/east-africa-regional",
		 "country": "KE", "region": "East Africa", "source_type": "government_federal",
		 "geographic_scope": "regional", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["usaid", "east-africa"]},
		{"name": "USAID Southern Africa Regional Mission", "url": "https://www.usaid.gov/southern-africa-regional",
		 "country": "ZA", "region": "Southern Africa", "source_type": "government_federal",
		 "geographic_scope": "regional", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["usaid", "southern-africa"]},
		{"name": "EU Delegations in Africa (EuropeAid)",
		 "url": "https://ec.europa.eu/international-partnerships/funding/funding-opportunities_en",
		 "country": "BE", "region": "Pan-African", "source_type": "government_international",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 10,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["eu-aid", "development", "africa"]},
		{"name": "GIZ Africa Regional Programme Tenders",
		 "url": "https://www.giz.de/en/worldwide/africa.html",
		 "country": "DE", "region": "Pan-African", "source_type": "government_federal",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 8,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["giz", "german-aid", "africa"]},
		{"name": "AFD Africa Operations Tenders",
		 "url": "https://www.afd.fr/en/calls-for-tender",
		 "country": "FR", "region": "Pan-African", "source_type": "government_federal",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 5,
		 "language": "fr", "recommended_scraper": "universal",
		 "tags": ["afd", "french-aid", "africa"]},
		{"name": "World Bank Africa East Region Tenders",
		 "url": "https://www.worldbank.org/en/region/afr",
		 "country": "US", "region": "East Africa", "source_type": "government_international",
		 "geographic_scope": "regional", "typical_opportunities_per_day": 8,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["world-bank", "east-africa"]},
		{"name": "UN Resident Coordinator Africa Tenders (OCHA/UN)",
		 "url": "https://reliefweb.int/country/africa",
		 "country": "CH", "region": "Pan-African", "source_type": "government_international",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 10,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["un", "humanitarian", "africa"]},
	]


def get_african_financial_sector() -> list[dict[str, Any]]:
	"""African financial sector institutions and fintech/banking procurement."""
	return [
		{"name": "African Development Fund (ADF) Tenders",
		 "url": "https://www.afdb.org/en/projects-and-operations/procurement",
		 "country": "CI", "region": "Pan-African", "source_type": "government_international",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["afdb", "concessional-lending", "africa"]},
		{"name": "Standard Bank Group Procurement (Africa)",
		 "url": "https://www.standardbank.com/",
		 "country": "ZA", "region": "Pan-African", "source_type": "corporate",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 3,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["banking", "finance", "africa"]},
		{"name": "Equity Bank Group Procurement (East Africa)",
		 "url": "https://equitygroupholdings.com/",
		 "country": "KE", "region": "East Africa", "source_type": "corporate",
		 "geographic_scope": "regional", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["banking", "fintech", "east-africa"]},
		{"name": "Ecobank Pan-African Procurement",
		 "url": "https://www.ecobank.com/",
		 "country": "TG", "region": "Pan-African", "source_type": "corporate",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["banking", "finance", "pan-african"]},
		{"name": "Mo Ibrahim Foundation Grants",
		 "url": "https://mo.ibrahim.foundation/",
		 "country": "GB", "region": "Pan-African", "source_type": "foundation",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 1,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["governance", "africa", "prize"]},
		{"name": "Tony Elumelu Foundation (TEF) Grants",
		 "url": "https://www.tonyelumelufoundation.org/tef-programme/apply",
		 "country": "NG", "region": "Pan-African", "source_type": "foundation",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["entrepreneurship", "africa", "grants"]},
		{"name": "Dangote Foundation Grants",
		 "url": "https://alicedangote.org/",
		 "country": "NG", "region": "West Africa", "source_type": "foundation",
		 "geographic_scope": "regional", "typical_opportunities_per_day": 1,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["health", "education", "nigeria"]},
	]


def get_country_sub_regional_portals() -> list[dict[str, Any]]:
	"""Sub-national portals for Ethiopia, Egypt, Ghana, and Tanzania."""
	return [
		# ── Ethiopia Regional States ───────────────────────────────────────────
		{"name": "Oromia Regional State Procurement (Ethiopia)",
		 "url": "https://www.oromia.gov.et/",
		 "country": "ET", "region": "East Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 8,
		 "language": "am", "recommended_scraper": "universal"},
		{"name": "Amhara Regional State Tenders (Ethiopia)",
		 "url": "https://www.amhara.gov.et/",
		 "country": "ET", "region": "East Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 6,
		 "language": "am", "recommended_scraper": "universal"},
		{"name": "SNNPR Regional State Procurement (Ethiopia)",
		 "url": "https://www.snnpr.gov.et/",
		 "country": "ET", "region": "East Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 5,
		 "language": "am", "recommended_scraper": "universal"},
		{"name": "Tigray Regional State Tenders (Ethiopia)",
		 "url": "https://www.tigray.gov.et/",
		 "country": "ET", "region": "East Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 4,
		 "language": "ti", "recommended_scraper": "universal"},
		{"name": "Addis Ababa City Administration Tenders",
		 "url": "https://www.addisababa.gov.et/",
		 "country": "ET", "region": "East Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 10,
		 "language": "am", "recommended_scraper": "universal"},
		{"name": "Dire Dawa City Council Tenders (Ethiopia)",
		 "url": "https://www.diredawa.gov.et/",
		 "country": "ET", "region": "East Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 3,
		 "language": "am", "recommended_scraper": "universal"},

		# ── Egypt Governorates ─────────────────────────────────────────────────
		{"name": "Cairo Governorate Procurement",
		 "url": "https://www.cairo.gov.eg/",
		 "country": "EG", "region": "North Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 10,
		 "language": "ar", "recommended_scraper": "universal"},
		{"name": "Giza Governorate Tenders",
		 "url": "https://www.giza.gov.eg/",
		 "country": "EG", "region": "North Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 8,
		 "language": "ar", "recommended_scraper": "universal"},
		{"name": "Alexandria Governorate Procurement",
		 "url": "https://www.alex.gov.eg/",
		 "country": "EG", "region": "North Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 8,
		 "language": "ar", "recommended_scraper": "universal"},
		{"name": "Luxor Governorate Tenders",
		 "url": "https://www.luxor.gov.eg/",
		 "country": "EG", "region": "North Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 3,
		 "language": "ar", "recommended_scraper": "universal"},
		{"name": "Egypt e-Finance Government Procurement",
		 "url": "https://www.e-finance.com.eg/",
		 "country": "EG", "region": "North Africa", "source_type": "government_federal",
		 "geographic_scope": "national", "typical_opportunities_per_day": 15,
		 "language": "ar", "recommended_scraper": "universal",
		 "notes": "Egypt's digital procurement transformation platform"},

		# ── Ghana Regions ─────────────────────────────────────────────────────
		{"name": "Accra Metropolitan Assembly Tenders",
		 "url": "https://www.ama.ghanadistricts.gov.gh/",
		 "country": "GH", "region": "West Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 6,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Kumasi Metropolitan Assembly Tenders",
		 "url": "https://www.kma.ghanadistricts.gov.gh/",
		 "country": "GH", "region": "West Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Ashanti Regional Coordinating Council Tenders",
		 "url": "https://ashanti.ghanadistricts.gov.gh/",
		 "country": "GH", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 5,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Greater Accra Regional Coordinating Council",
		 "url": "https://greateraccra.ghanadistricts.gov.gh/",
		 "country": "GH", "region": "West Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 6,
		 "language": "en", "recommended_scraper": "universal"},
		{"name": "Ghana Districts Portal (All Regions)",
		 "url": "https://www.ghanadistricts.gov.gh/",
		 "country": "GH", "region": "West Africa", "source_type": "government_federal",
		 "geographic_scope": "national", "typical_opportunities_per_day": 20,
		 "language": "en", "recommended_scraper": "universal",
		 "notes": "National aggregator for all Ghana district assembly tenders"},

		# ── Tanzania Regions ───────────────────────────────────────────────────
		{"name": "Dar es Salaam City Council Tenders",
		 "url": "https://www.dcc.go.tz/",
		 "country": "TZ", "region": "East Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 8,
		 "language": "sw", "recommended_scraper": "universal"},
		{"name": "Arusha City Council Tenders (Tanzania)",
		 "url": "https://www.arushacity.go.tz/",
		 "country": "TZ", "region": "East Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 4,
		 "language": "sw", "recommended_scraper": "universal"},
		{"name": "Mwanza City Council Procurement (Tanzania)",
		 "url": "https://www.mwanza.go.tz/",
		 "country": "TZ", "region": "East Africa", "source_type": "government_local",
		 "geographic_scope": "municipal", "typical_opportunities_per_day": 4,
		 "language": "sw", "recommended_scraper": "universal"},
		{"name": "Tanzania President's Office Regional Administration",
		 "url": "https://www.pmoralg.go.tz/",
		 "country": "TZ", "region": "East Africa", "source_type": "government_federal",
		 "geographic_scope": "national", "typical_opportunities_per_day": 10,
		 "language": "sw", "recommended_scraper": "universal",
		 "notes": "Aggregates tenders from all Tanzania regional authorities"},
		{"name": "Zanzibar Government Procurement (PPRA)",
		 "url": "https://www.zanzibar.go.tz/",
		 "country": "TZ", "region": "East Africa", "source_type": "government_state",
		 "geographic_scope": "state_provincial", "typical_opportunities_per_day": 5,
		 "language": "sw", "recommended_scraper": "universal"},
	]


def get_african_education_agriculture() -> list[dict[str, Any]]:
	"""African education, agriculture, and food security institutions."""
	return [
		{"name": "AGRA (Alliance for a Green Revolution in Africa) Grants",
		 "url": "https://agra.org/",
		 "country": "KE", "region": "Pan-African", "source_type": "foundation",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 3,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["agriculture", "food-security", "africa"]},
		{"name": "IITA (International Institute of Tropical Agriculture) Tenders",
		 "url": "https://www.iita.org/",
		 "country": "NG", "region": "Pan-African", "source_type": "nonprofit",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 3,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["agriculture", "research", "africa"]},
		{"name": "ILRI (International Livestock Research Institute) Tenders",
		 "url": "https://www.ilri.org/procurement",
		 "country": "KE", "region": "Pan-African", "source_type": "nonprofit",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 3,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["livestock", "research", "africa"]},
		{"name": "CIMMYT Africa (Maize and Wheat Research) Tenders",
		 "url": "https://www.cimmyt.org/",
		 "country": "KE", "region": "Pan-African", "source_type": "nonprofit",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["agriculture", "research", "maize"]},
		{"name": "African Union of Broadcasting (AUB) Tenders",
		 "url": "https://www.aub.org/",
		 "country": "SN", "region": "Pan-African", "source_type": "government_international",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 1,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["media", "broadcasting", "au"]},
		{"name": "Pan-African University (PAU) Procurement",
		 "url": "https://pau.africa/procurement/",
		 "country": "CM", "region": "Pan-African", "source_type": "government_international",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["education", "au", "university"]},
		{"name": "African Export Promotion Programme (AFREXIMBANK)",
		 "url": "https://www.afreximbank.com/knowledge/trade-finance/",
		 "country": "EG", "region": "Pan-African", "source_type": "government_international",
		 "geographic_scope": "continental", "typical_opportunities_per_day": 2,
		 "language": "en", "recommended_scraper": "universal",
		 "tags": ["trade", "export", "finance"]},
	]
