"""
Global Grant-Giving Organizations Registry

Covers philanthropic foundations, bilateral/multilateral donor agencies,
research funders, government grant portals, and emerging-market funds
that publish open calls for proposals, RFPs, or grant opportunities.

Grouped by funder type for easy filtering.
"""

from typing import Any


def get_us_foundations() -> list[dict[str, Any]]:
	"""Major US philanthropic foundations."""
	return [
		{"name": "W.K. Kellogg Foundation Grants", "url": "https://www.wkkf.org/grants",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["health", "food", "education", "children"]},
		{"name": "Packard Foundation Grants", "url": "https://www.packard.org/grants/",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["conservation", "science", "reproductive-health"]},
		{"name": "Gordon & Betty Moore Foundation", "url": "https://www.moore.org/grants",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["science", "environment", "healthcare"]},
		{"name": "Simons Foundation Grants", "url": "https://www.simonsfoundation.org/",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["mathematics", "science", "autism"]},
		{"name": "Walton Family Foundation Grants", "url": "https://www.waltonfamilyfoundation.org/grants",
		 "country": "US", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["education", "environment", "fishing"]},
		{"name": "Carnegie Corporation of New York", "url": "https://www.carnegie.org/grants/",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["education", "democracy", "africa"]},
		{"name": "Alfred P. Sloan Foundation", "url": "https://sloan.org/grants",
		 "country": "US", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["science", "technology", "economics"]},
		{"name": "Pew Charitable Trusts Grants", "url": "https://www.pewtrusts.org/en/about/grants",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["environment", "health", "civic"]},
		{"name": "Annie E. Casey Foundation Grants", "url": "https://www.aecf.org/work/grants",
		 "country": "US", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["children", "families", "economic-mobility"]},
		{"name": "Kresge Foundation Grants", "url": "https://kresge.org/grants-social-investments/",
		 "country": "US", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["arts", "education", "environment"]},
		{"name": "Knight Foundation Grants", "url": "https://knightfoundation.org/grants/",
		 "country": "US", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["journalism", "arts", "technology"]},
		{"name": "Doris Duke Charitable Foundation", "url": "https://www.ddcf.org/grant-programs/",
		 "country": "US", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 1, "language": "en", "recommended_scraper": "universal",
		 "tags": ["arts", "environment", "health"]},
		{"name": "Skoll Foundation Grants", "url": "https://skoll.org/about/apply/",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 1, "language": "en", "recommended_scraper": "universal",
		 "tags": ["social-entrepreneurship", "development"]},
		{"name": "Omidyar Network / Luminate Grants", "url": "https://omidyar.com/",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 1, "language": "en", "recommended_scraper": "universal",
		 "tags": ["democracy", "civic-tech", "financial-inclusion"]},
		{"name": "Arcadia Fund Grants", "url": "https://www.arcadiafund.org.uk/grants/",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 1, "language": "en", "recommended_scraper": "universal",
		 "tags": ["environment", "open-access", "cultural-heritage"]},
		{"name": "Schmidt Futures Grants", "url": "https://schmidtfutures.com/",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 1, "language": "en", "recommended_scraper": "universal",
		 "tags": ["science", "technology", "policy"]},
		{"name": "Rockefeller Brothers Fund", "url": "https://www.rbf.org/grants",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 1, "language": "en", "recommended_scraper": "universal",
		 "tags": ["democracy", "peace", "environment"]},
		{"name": "Atlantic Philanthropies (legacy archive)", "url": "https://www.atlanticphilanthropies.org/",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 1, "language": "en", "recommended_scraper": "universal",
		 "tags": ["aging", "health", "human-rights"]},
		{"name": "Oak Foundation Grants", "url": "https://oakfnd.org/apply-for-a-grant/",
		 "country": "CH", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["climate", "children", "housing"]},
	]


def get_european_foundations() -> list[dict[str, Any]]:
	"""European philanthropic foundations and research funders."""
	return [
		{"name": "Nuffield Foundation Grants (UK)", "url": "https://www.nuffieldfoundation.org/funding",
		 "country": "GB", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["education", "family", "justice"]},
		{"name": "Joseph Rowntree Foundation (UK)", "url": "https://www.jrf.org.uk/",
		 "country": "GB", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["poverty", "housing", "employment"]},
		{"name": "Paul Hamlyn Foundation (UK)", "url": "https://www.phf.org.uk/funds/",
		 "country": "GB", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["arts", "education", "migrants"]},
		{"name": "Children's Investment Fund Foundation (CIFF)", "url": "https://ciff.org/",
		 "country": "GB", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["children", "climate", "health"]},
		{"name": "Calouste Gulbenkian Foundation", "url": "https://gulbenkian.pt/en/grants-and-projects/",
		 "country": "PT", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "pt",
		 "recommended_scraper": "universal", "tags": ["arts", "education", "science"]},
		{"name": "Sigrid Rausing Trust Grants", "url": "https://www.sigrid-rausing-trust.org/",
		 "country": "GB", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 1, "language": "en", "recommended_scraper": "universal",
		 "tags": ["human-rights", "environment"]},
		{"name": "Robert Bosch Foundation Grants", "url": "https://www.bosch-stiftung.de/en/grants",
		 "country": "DE", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "de", "recommended_scraper": "universal",
		 "tags": ["education", "health", "migration"]},
		{"name": "Bernard van Leer Foundation", "url": "https://bernardvanleer.org/apply/",
		 "country": "NL", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 1, "language": "en", "recommended_scraper": "universal",
		 "tags": ["early-childhood", "urban-development"]},
		{"name": "European Cultural Foundation Grants", "url": "https://culturalfoundation.eu/",
		 "country": "NL", "source_type": "foundation", "geographic_scope": "continental",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["culture", "arts", "democracy"]},
		{"name": "Volkswagen Foundation (VolkswagenStiftung)", "url": "https://www.volkswagenstiftung.de/en/funding",
		 "country": "DE", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "de", "recommended_scraper": "universal",
		 "tags": ["science", "research"]},
		{"name": "Compagnia di San Paolo Grants (Italy)", "url": "https://www.compagniadisanpaolo.it/eng/Erogazioni",
		 "country": "IT", "source_type": "foundation", "geographic_scope": "regional",
		 "typical_opportunities_per_day": 2, "language": "it", "recommended_scraper": "universal",
		 "tags": ["arts", "research", "welfare"]},
		{"name": "Fondation de France Grants", "url": "https://www.fondationdefrance.org/",
		 "country": "FR", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 3, "language": "fr", "recommended_scraper": "universal",
		 "tags": ["health", "culture", "research"]},
		{"name": "EEA and Norway Grants", "url": "https://www.eeagrants.org/",
		 "country": "NO", "source_type": "foundation", "geographic_scope": "continental",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["environment", "research", "social"]},
	]


def get_middle_east_gulf_funds() -> list[dict[str, Any]]:
	"""Gulf and Middle Eastern donor/grant institutions."""
	return [
		{"name": "Qatar Foundation Research Grants", "url": "https://www.qf.org.qa/research",
		 "country": "QA", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["research", "education", "science"]},
		{"name": "Mohammed Bin Rashid Al Maktoum Global Initiatives", "url": "https://www.mbrgi.ae/",
		 "country": "AE", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["humanitarian", "education", "development"]},
		{"name": "AGFUND (Arab Gulf Programme for Development)", "url": "https://www.agfund.org/en/grants",
		 "country": "SA", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["development", "humanitarian", "arab-world"]},
		{"name": "Kuwait Fund for Arab Economic Development", "url": "https://www.kuwait-fund.org/",
		 "country": "KW", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["development-finance", "infrastructure"]},
		{"name": "Saudi Fund for Development (SFD)", "url": "https://www.sfd.gov.sa/en/",
		 "country": "SA", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["development-finance", "infrastructure"]},
		{"name": "OPEC Fund for International Development", "url": "https://opecfund.org/procurement",
		 "country": "AT", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["development-finance", "energy"]},
		{"name": "Islamic Development Bank (IsDB) Procurement", "url": "https://www.isdb.org/about-isdb/procurement",
		 "country": "SA", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 5, "language": "en", "recommended_scraper": "universal",
		 "tags": ["islamic-finance", "development", "infrastructure"]},
		{"name": "Abu Dhabi Fund for Development (ADFD)", "url": "https://www.adfd.ae/english/Pages/Home.aspx",
		 "country": "AE", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 2, "language": "en", "recommended_scraper": "universal",
		 "tags": ["development-finance", "infrastructure"]},
	]


def get_research_funders() -> list[dict[str, Any]]:
	"""Government and international research funding agencies."""
	return [
		{"name": "European Research Council (ERC)", "url": "https://erc.europa.eu/apply-grant",
		 "country": "BE", "source_type": "foundation", "geographic_scope": "continental",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["research", "science", "europe"]},
		{"name": "Horizon Europe Funding Portal", "url": "https://ec.europa.eu/info/funding-tenders/opportunities/portal/",
		 "country": "BE", "source_type": "foundation", "geographic_scope": "continental",
		 "typical_opportunities_per_day": 10, "language": "en", "recommended_scraper": "universal",
		 "tags": ["research", "innovation", "europe"]},
		{"name": "UK Research and Innovation (UKRI)", "url": "https://www.ukri.org/opportunity/",
		 "country": "GB", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 5, "language": "en", "recommended_scraper": "universal",
		 "tags": ["research", "innovation", "uk"]},
		{"name": "Australian Research Council (ARC) Grants", "url": "https://www.arc.gov.au/grants-and-funding",
		 "country": "AU", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["research", "science", "australia"]},
		{"name": "Human Frontier Science Program (HFSP)", "url": "https://www.hfsp.org/funding",
		 "country": "FR", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 1, "language": "en", "recommended_scraper": "universal",
		 "tags": ["life-science", "research"]},
		{"name": "Kavli Foundation Grants", "url": "https://www.kavlifoundation.org/",
		 "country": "US", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 1, "language": "en", "recommended_scraper": "universal",
		 "tags": ["astrophysics", "nanoscience", "neuroscience"]},
		{"name": "Wellcome Trust Funding (Extended)", "url": "https://wellcome.org/grant-funding/schemes",
		 "country": "GB", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["health-research", "biomedical"]},
		{"name": "Canada Research Chairs Program", "url": "https://www.chairs-chaires.gc.ca/",
		 "country": "CA", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["research", "academic", "canada"]},
		{"name": "Japanese Society for the Promotion of Science (JSPS)", "url": "https://www.jsps.go.jp/english/e-grants/index.html",
		 "country": "JP", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["research", "science", "japan"]},
		{"name": "German Research Foundation (DFG) Grants", "url": "https://www.dfg.de/en/research_funding/programmes/index.html",
		 "country": "DE", "source_type": "foundation", "geographic_scope": "global",
		 "typical_opportunities_per_day": 5, "language": "de", "recommended_scraper": "universal",
		 "tags": ["research", "science", "germany"]},
		{"name": "Swedish Research Council (VR) Grants", "url": "https://www.vr.se/english/applying-for-funding.html",
		 "country": "SE", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 3, "language": "sv", "recommended_scraper": "universal",
		 "tags": ["research", "science", "sweden"]},
		{"name": "Swiss National Science Foundation (SNSF)", "url": "https://www.snf.ch/en/funding",
		 "country": "CH", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["research", "science", "switzerland"]},
		{"name": "National Research Foundation South Africa (NRF)", "url": "https://www.nrf.ac.za/funding/",
		 "country": "ZA", "source_type": "foundation", "geographic_scope": "national",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["research", "science", "africa"]},
	]


def get_bilateral_donor_agencies() -> list[dict[str, Any]]:
	"""Bilateral donor agencies with open calls for proposals."""
	return [
		{"name": "USAID Business Forecast", "url": "https://www.usaid.gov/work-usaid/business-forecast",
		 "country": "US", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 5, "language": "en", "recommended_scraper": "universal",
		 "tags": ["usaid", "development", "bilateral"]},
		{"name": "FCDO (UK Foreign, Commonwealth & Development Office) Funding", "url": "https://www.gov.uk/government/organisations/foreign-commonwealth-development-office",
		 "country": "GB", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 5, "language": "en", "recommended_scraper": "universal",
		 "tags": ["uk-aid", "development", "bilateral"]},
		{"name": "GIZ (German Development Agency) Procurement", "url": "https://www.giz.de/en/workingwithgiz/procurement.html",
		 "country": "DE", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 8, "language": "en", "recommended_scraper": "universal",
		 "tags": ["german-aid", "development", "bilateral"]},
		{"name": "AFD (Agence Française de Développement) Tenders", "url": "https://www.afd.fr/en/calls-for-tender",
		 "country": "FR", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 5, "language": "fr", "recommended_scraper": "universal",
		 "tags": ["french-aid", "development", "bilateral"]},
		{"name": "SIDA (Swedish International Development) Grants", "url": "https://www.sida.se/en/for-partners/apply-for-funding",
		 "country": "SE", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["swedish-aid", "development", "bilateral"]},
		{"name": "Norad (Norwegian Aid) Grants", "url": "https://www.norad.no/en/front/funding/",
		 "country": "NO", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["norwegian-aid", "development", "bilateral"]},
		{"name": "DANIDA (Danish Aid) Grants", "url": "https://um.dk/en/danida/partners/calls-for-applications",
		 "country": "DK", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["danish-aid", "development", "bilateral"]},
		{"name": "Global Affairs Canada Grants", "url": "https://www.international.gc.ca/world-monde/funding-financement/index.aspx",
		 "country": "CA", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["canadian-aid", "development", "bilateral"]},
		{"name": "JICA (Japan International Cooperation Agency) Procurement", "url": "https://www.jica.go.jp/english/business/consulting/index.html",
		 "country": "JP", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 5, "language": "en", "recommended_scraper": "universal",
		 "tags": ["japanese-aid", "development", "bilateral"]},
		{"name": "KfW (German Development Bank) Tenders", "url": "https://www.kfw-entwicklungsbank.de/International-financing/KfW-Entwicklungsbank/Procurement/",
		 "country": "DE", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 5, "language": "en", "recommended_scraper": "universal",
		 "tags": ["german-aid", "development-finance", "bilateral"]},
		{"name": "DFAT (Australian Aid) Grants", "url": "https://www.dfat.gov.au/aid/topics/grants-and-tenders",
		 "country": "AU", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 5, "language": "en", "recommended_scraper": "universal",
		 "tags": ["australian-aid", "development", "pacific"]},
		{"name": "USDA Foreign Agricultural Service (FAS) Grants", "url": "https://www.fas.usda.gov/programs/",
		 "country": "US", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["agriculture", "food-security", "us-aid"]},
		{"name": "MCC (Millennium Challenge Corporation) Procurement", "url": "https://www.mcc.gov/",
		 "country": "US", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["us-aid", "infrastructure", "development"]},
		{"name": "DFC (US International Development Finance Corp) Tenders", "url": "https://www.dfc.gov/",
		 "country": "US", "source_type": "government_federal", "geographic_scope": "global",
		 "typical_opportunities_per_day": 3, "language": "en", "recommended_scraper": "universal",
		 "tags": ["us-aid", "private-sector", "development-finance"]},
	]


def get_grant_aggregators() -> list[dict[str, Any]]:
	"""Platforms that aggregate grant opportunities from multiple funders."""
	return [
		{"name": "EU Funding & Tenders Portal (Horizon, LIFE, etc.)", "url": "https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/home",
		 "country": "BE", "source_type": "aggregator", "geographic_scope": "global",
		 "typical_opportunities_per_day": 20, "language": "en", "recommended_scraper": "playwright_stealth",
		 "tags": ["aggregator", "eu", "research", "innovation"]},
		{"name": "FundingBox (European SME grants)", "url": "https://fundingbox.com/open-calls/",
		 "country": "ES", "source_type": "aggregator", "geographic_scope": "continental",
		 "typical_opportunities_per_day": 5, "language": "en", "recommended_scraper": "universal",
		 "tags": ["aggregator", "europe", "sme", "startups"]},
		{"name": "GrantConnect (Canadian Government Grants)", "url": "https://www.grants-contributions.canada.ca/",
		 "country": "CA", "source_type": "aggregator", "geographic_scope": "national",
		 "typical_opportunities_per_day": 10, "language": "en", "recommended_scraper": "universal",
		 "tags": ["aggregator", "canada", "government"]},
		{"name": "Submittable (Open Calls Platform)", "url": "https://www.submittable.com/discover/",
		 "country": "US", "source_type": "aggregator", "geographic_scope": "global",
		 "typical_opportunities_per_day": 15, "language": "en", "recommended_scraper": "universal",
		 "tags": ["aggregator", "arts", "nonprofits", "social"]},
		{"name": "GrantStation (NGO grant database)", "url": "https://grantstation.com/",
		 "country": "US", "source_type": "aggregator", "geographic_scope": "global",
		 "requires_subscription": True, "typical_opportunities_per_day": 50,
		 "language": "en", "recommended_scraper": "playwright_stealth",
		 "tags": ["aggregator", "nonprofits", "foundations"]},
		{"name": "TGCI (The Grantsmanship Center)", "url": "https://www.tgci.com/funding-sources",
		 "country": "US", "source_type": "aggregator", "geographic_scope": "national",
		 "typical_opportunities_per_day": 10, "language": "en", "recommended_scraper": "universal",
		 "tags": ["aggregator", "nonprofits", "training"]},
		{"name": "Fundsforngos.org", "url": "https://www2.fundsforngos.org/",
		 "country": "US", "source_type": "aggregator", "geographic_scope": "global",
		 "typical_opportunities_per_day": 15, "language": "en", "recommended_scraper": "universal",
		 "tags": ["aggregator", "ngos", "developing-world"]},
		{"name": "Akvo RSR (Development Project Database)", "url": "https://rsr.akvo.org/en/projects/",
		 "country": "NL", "source_type": "aggregator", "geographic_scope": "global",
		 "typical_opportunities_per_day": 5, "language": "en", "recommended_scraper": "universal",
		 "tags": ["aggregator", "development", "projects"]},
		{"name": "Development Aid (DA) Tenders & Grants", "url": "https://www.developmentaid.org/",
		 "country": "BE", "source_type": "aggregator", "geographic_scope": "global",
		 "requires_subscription": True, "typical_opportunities_per_day": 50,
		 "language": "en", "recommended_scraper": "playwright_stealth",
		 "tags": ["aggregator", "development", "tenders", "grants"]},
	]
