"""
Pacific Islands and Caribbean Procurement Sources Registry

Covers all Pacific Island states/territories and all Caribbean nations/territories.
"""

from typing import Any


def get_pacific_sources() -> list[dict[str, Any]]:
	"""Return national procurement portals for Pacific Island states and territories."""
	return [
		# ── Melanesia ──────────────────────────────────────────────────────────
		{
			"name": "Papua New Guinea CSTB (Central Supply & Tenders Board)",
			"url": "https://cstb.gov.pg/",
			"country": "PG", "region": "Melanesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 10, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Fiji Government Procurement",
			"url": "https://www.govtender.gov.fj/",
			"country": "FJ", "region": "Melanesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 5, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Solomon Islands Ministry of Finance Tenders",
			"url": "https://www.mof.gov.sb/",
			"country": "SB", "region": "Melanesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "en",
			"recommended_scraper": "universal",
			"notes": "Tenders via Ministry of Finance portal",
		},
		{
			"name": "Vanuatu Government Tenders",
			"url": "https://www.gov.vu/index.php/tenders",
			"country": "VU", "region": "Melanesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "New Caledonia Public Procurement",
			"url": "https://www.marchespublics.nc/",
			"country": "NC", "region": "Melanesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 4, "language": "fr",
			"recommended_scraper": "universal",
			"notes": "French territory",
		},

		# ── Polynesia ──────────────────────────────────────────────────────────
		{
			"name": "Samoa Ministry of Finance Tenders",
			"url": "https://www.mof.gov.ws/",
			"country": "WS", "region": "Polynesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Tonga Ministry of Finance Procurement",
			"url": "https://www.finance.gov.to/",
			"country": "TO", "region": "Polynesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "French Polynesia Public Procurement",
			"url": "https://www.marche-public.pf/",
			"country": "PF", "region": "Polynesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 5, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Cook Islands Government Tenders",
			"url": "https://www.cookislands.gov.ck/",
			"country": "CK", "region": "Polynesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Niue Government Tenders",
			"url": "https://www.gov.nu/",
			"country": "NU", "region": "Polynesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Wallis and Futuna Public Procurement",
			"url": "https://www.wallis-et-futuna.pref.gouv.fr/",
			"country": "WF", "region": "Polynesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "fr",
			"recommended_scraper": "universal",
			"notes": "French territory",
		},
		{
			"name": "American Samoa Government Procurement",
			"url": "https://www.americansamoa.gov/government/",
			"country": "AS", "region": "Polynesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
			"notes": "US territory",
		},

		# ── Micronesia ─────────────────────────────────────────────────────────
		{
			"name": "Kiribati Ministry of Finance Tenders",
			"url": "https://www.mfed.gov.ki/",
			"country": "KI", "region": "Micronesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Federated States of Micronesia Procurement",
			"url": "https://www.fsmgov.org/",
			"country": "FM", "region": "Micronesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Marshall Islands Government Tenders",
			"url": "https://www.mif.fm/",
			"country": "MH", "region": "Micronesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Palau Government Procurement",
			"url": "https://www.palaugov.pw/",
			"country": "PW", "region": "Micronesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Nauru Government Tenders",
			"url": "https://www.naurugov.nr/",
			"country": "NR", "region": "Micronesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Guam Government Procurement",
			"url": "https://gprocurement.guam.gov/",
			"country": "GU", "region": "Micronesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "en",
			"recommended_scraper": "universal",
			"notes": "US territory",
		},
		{
			"name": "CNMI (Northern Mariana Islands) Procurement",
			"url": "https://www.cnmilaw.org/procurement.html",
			"country": "MP", "region": "Micronesia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 1, "language": "en",
			"recommended_scraper": "universal",
			"notes": "US commonwealth",
		},

		# ── Asia-Pacific (Timor-Leste) ─────────────────────────────────────────
		{
			"name": "Timor-Leste National Procurement Commission (AIFAESA)",
			"url": "https://www.aifaesa.gov.tl/",
			"country": "TL", "region": "Southeast Asia",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "pt",
			"recommended_scraper": "universal",
		},

		# ── Pacific Regional Bodies ────────────────────────────────────────────
		{
			"name": "Pacific Community (SPC) Procurement",
			"url": "https://www.spc.int/about-us/procurement",
			"country": "NC", "region": "Pan-Pacific",
			"source_type": "government_international", "geographic_scope": "continental",
			"typical_opportunities_per_day": 3, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Pacific Islands Forum Secretariat Tenders",
			"url": "https://www.forumsec.org/procurement/",
			"country": "FJ", "region": "Pan-Pacific",
			"source_type": "government_international", "geographic_scope": "continental",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "ADB Pacific Operations Procurement",
			"url": "https://www.adb.org/business/opportunities/consulting/pacific",
			"country": "PH", "region": "Pan-Pacific",
			"source_type": "government_international", "geographic_scope": "continental",
			"typical_opportunities_per_day": 3, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "PRIF (Pacific Region Infrastructure Facility) Tenders",
			"url": "https://www.theprif.org/procurement",
			"country": "AU", "region": "Pan-Pacific",
			"source_type": "government_international", "geographic_scope": "continental",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
		},
	]


def get_caribbean_sources() -> list[dict[str, Any]]:
	"""Return national and regional procurement portals for the Caribbean."""
	return [
		# ── Greater Antilles ───────────────────────────────────────────────────
		{
			"name": "Jamaica National Contracts Commission (NCC)",
			"url": "https://www.ncc.gov.jm/",
			"country": "JM", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Trinidad & Tobago Office of Procurement Regulation",
			"url": "https://www.opr.gov.tt/",
			"country": "TT", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 10, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Cuba Electronic Commerce Portal",
			"url": "https://www.cubacomercio.cu/",
			"country": "CU", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "es",
			"recommended_scraper": "universal",
		},
		{
			"name": "Dominican Republic DGCP (Public Procurement)",
			"url": "https://www.dgcp.gob.do/",
			"country": "DO", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 20, "language": "es",
			"recommended_scraper": "universal",
		},
		{
			"name": "Haiti CNMP (National Commission for Public Markets)",
			"url": "https://www.cnmp.gouv.ht/",
			"country": "HT", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 5, "language": "fr",
			"recommended_scraper": "universal",
		},
		{
			"name": "Puerto Rico Government Procurement",
			"url": "https://www2.pr.gov/presupuesto/contratos/Pages/default.aspx",
			"country": "PR", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 5, "language": "es",
			"recommended_scraper": "universal",
			"notes": "US territory",
		},

		# ── Lesser Antilles (OECS + others) ───────────────────────────────────
		{
			"name": "Barbados National Procurement Commission",
			"url": "https://www.npc.gov.bb/",
			"country": "BB", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 5, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Guyana National Procurement and Tender Administration Board",
			"url": "https://www.nptab.gov.gy/",
			"country": "GY", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 8, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Belize Finance Ministry Tenders",
			"url": "https://www.mof.gov.bz/",
			"country": "BZ", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 4, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Suriname Government Procurement",
			"url": "https://www.gov.sr/",
			"country": "SR", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "nl",
			"recommended_scraper": "universal",
		},
		{
			"name": "Bahamas Ministry of Finance Tenders",
			"url": "https://www.bahamas.gov.bs/wps/portal/public/Tenders",
			"country": "BS", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 4, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Antigua and Barbuda Government Tenders",
			"url": "https://ab.gov.ag/",
			"country": "AG", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Saint Lucia Government Procurement",
			"url": "https://www.govt.lc/",
			"country": "LC", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Saint Vincent and the Grenadines Government Tenders",
			"url": "https://www.gov.vc/",
			"country": "VC", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Grenada Government Procurement",
			"url": "https://www.gov.gd/",
			"country": "GD", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Dominica Government Tenders",
			"url": "https://www.dominica.gov.dm/",
			"country": "DM", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "Saint Kitts and Nevis Government Procurement",
			"url": "https://www.gov.kn/",
			"country": "KN", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
		},

		# ── UK/Dutch/French Territories ────────────────────────────────────────
		{
			"name": "Cayman Islands Government Procurement",
			"url": "https://www.gov.ky/",
			"country": "KY", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "en",
			"recommended_scraper": "universal",
			"notes": "UK overseas territory",
		},
		{
			"name": "Bermuda Government Contracts",
			"url": "https://www.gov.bm/",
			"country": "BM", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "en",
			"recommended_scraper": "universal",
			"notes": "UK overseas territory",
		},
		{
			"name": "British Virgin Islands Government Tenders",
			"url": "https://www.bvi.gov.vg/",
			"country": "VG", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
			"notes": "UK overseas territory",
		},
		{
			"name": "Turks and Caicos Government Procurement",
			"url": "https://www.gov.tc/",
			"country": "TC", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
			"notes": "UK overseas territory",
		},
		{
			"name": "US Virgin Islands Government Procurement",
			"url": "https://www.vi.gov/",
			"country": "VI", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 3, "language": "en",
			"recommended_scraper": "universal",
			"notes": "US territory",
		},
		{
			"name": "Martinique Public Procurement (BOAMP)",
			"url": "https://www.boamp.fr/",
			"country": "MQ", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 4, "language": "fr",
			"recommended_scraper": "universal",
			"notes": "French overseas department; uses French national procurement system",
		},
		{
			"name": "Guadeloupe Public Procurement (BOAMP)",
			"url": "https://www.boamp.fr/",
			"country": "GP", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 4, "language": "fr",
			"recommended_scraper": "universal",
			"notes": "French overseas department; uses French national procurement system",
		},
		{
			"name": "Curaçao Government Procurement",
			"url": "https://www.gobiernu.cw/",
			"country": "CW", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "nl",
			"recommended_scraper": "universal",
		},
		{
			"name": "Aruba Government Procurement",
			"url": "https://www.aruba.aw/",
			"country": "AW", "region": "Caribbean",
			"source_type": "government_federal", "geographic_scope": "national",
			"typical_opportunities_per_day": 2, "language": "nl",
			"recommended_scraper": "universal",
		},

		# ── Caribbean Regional Bodies ──────────────────────────────────────────
		{
			"name": "Caribbean Development Bank (CDB) Procurement",
			"url": "https://www.caribank.org/business/procurement",
			"country": "BB", "region": "Pan-Caribbean",
			"source_type": "government_international", "geographic_scope": "regional",
			"typical_opportunities_per_day": 5, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "CARICOM Secretariat Tenders",
			"url": "https://caricom.org/procurement/",
			"country": "GY", "region": "Pan-Caribbean",
			"source_type": "government_international", "geographic_scope": "regional",
			"typical_opportunities_per_day": 3, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "OECS (Organisation of Eastern Caribbean States) Procurement",
			"url": "https://www.oecs.org/en/about-the-oecs/procurement",
			"country": "LC", "region": "Pan-Caribbean",
			"source_type": "government_international", "geographic_scope": "regional",
			"typical_opportunities_per_day": 2, "language": "en",
			"recommended_scraper": "universal",
		},
		{
			"name": "IDB (Inter-American Development Bank) Caribbean",
			"url": "https://www.iadb.org/en/procurement",
			"country": "US", "region": "Pan-Caribbean",
			"source_type": "government_international", "geographic_scope": "regional",
			"typical_opportunities_per_day": 5, "language": "en",
			"recommended_scraper": "universal",
		},
	]
