#!/usr/bin/env bash
# Fetches DocFusion secrets from OpenBao and writes deployment/.env.spare-2
# Run: ./deployment/scripts/fill-env.sh
# Requires: bao CLI in PATH, OpenBao at 62.169.25.77:8200, AppRole credentials

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/../.env.spare-2"

export BAO_ADDR="http://62.169.25.77:8200"
BAO_TOKEN=$(bao write -field=token auth/approle/login \
  role_id=78b01326-6401-e02e-b2c4-f329ad03c62d \
  secret_id=4ae98874-52f2-baea-7af1-93e5b0f50e2c)
export BAO_TOKEN

kv() { bao kv get -field="$2" "apps/docfusion/$1" 2>/dev/null || echo "MISSING_${1//\//_}_$2"; }

# DB URL built from parts to avoid double-fetching
DB_USER=$(kv database user)
DB_PASS=$(kv database password)

cat > "$OUT" << ENV
# DocFusion .env — spare-2 (161.97.124.202)
# Generated by fill-env.sh — do NOT commit this file
#   scp deployment/.env.spare-2 root@161.97.124.202:/root/docfusion/.env

# ── Application ────────────────────────────────────────────────
DEBUG=false
LOG_LEVEL=info
NODE_ENV=production
NEXT_TELEMETRY_DISABLED=1
ENVIRONMENT=production

# ── Application secrets ────────────────────────────────────────
JWT_SECRET=$(kv secrets jwt_secret)
ENCRYPTION_KEY=$(kv secrets encryption_key)
DOCFUSION_TENANT_HEADER_SECRET=$(kv secrets tenant_header_secret)

# ── Database (db.lindela.io — PostgreSQL 17 PRIMARY) ───────────
DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db.lindela.io:5432/docfusion

# ── LiteLLM gateway (ml/vault — 62.169.25.77) ──────────────────
LITELLM_URL=http://62.169.25.77:4000/v1
LITELLM_KEY=$(kv ai litellm_key)
LLM_MODEL=gpt-4o
LLM_FAST_MODEL=gpt-4o-mini
LLM_EMBEDDING_MODEL=text-embedding-ada-002

# ── Discovery services (search — 84.247.181.100) ───────────────
SEARXNG_URL=http://84.247.181.100:8888
FIRECRAWL_URL=http://84.247.181.100:3002
DOCLING_URL=http://84.247.181.100:3600

# ── Notifications (Stalwart SMTP — mail.lindela.io) ────────────
DIGEST_TO_EMAIL=nyimbi@gmail.com
SMTP_HOST=mail.lindela.io
SMTP_PORT=587
SMTP_USER=$(kv mail smtp_user)
SMTP_PASSWORD=$(kv mail smtp_password)
SMTP_FROM=$(kv mail smtp_from)

# ── Agent memory ────────────────────────────────────────────────
MEMORY_TTL_DAYS=30

# ── Storage (Linode E3 object store — docfusion-rfp) ───────────
LINODE_E3_BUCKET=$(kv infrastructure/minio bucket)
LINODE_E3_REGION=$(kv infrastructure/minio region)
LINODE_E3_ENDPOINT=$(kv infrastructure/minio endpoint)
LINODE_E3_ACCESS_KEY_ID=$(kv infrastructure/minio access_key_id)
LINODE_E3_SECRET_ACCESS_KEY=$(kv infrastructure/minio secret_access_key)

# ── Soketi (WebSocket — 84.247.181.100:6001) ───────────────────
PUSHER_APP_KEY=$(kv infrastructure/soketi app_key)
PUSHER_APP_SECRET=$(kv infrastructure/soketi app_secret)
PUSHER_APP_ID=$(kv infrastructure/soketi app_id)
PUSHER_HOST=84.247.181.100
PUSHER_PORT=6001

# ── Auth (Keycloak — auth.lindela.io) ──────────────────────────
NEXTAUTH_URL=http://161.97.124.202:3000
NEXTAUTH_SECRET=$(kv secrets nextauth_secret)
KEYCLOAK_ISSUER=https://auth.lindela.io/realms/pjs
KEYCLOAK_CLIENT_ID=$(kv auth keycloak_client_id)
KEYCLOAK_CLIENT_SECRET=$(kv auth keycloak_client_secret)
ENV

chmod 600 "$OUT"
echo "Written: $OUT"
