#!/usr/bin/env bash
# Populates deployment/.env.spare-2 from pass + OpenBao.
# Run: ./deployment/scripts/fill-env.sh
# Requires: pass, bao CLI

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/../.env.spare-2"

p() { pass "$1" | head -n1; }  # first-line-only shorthand (per pass convention)

# ── Helper: generate+store a secret in pass if not present ─────
# $1 = pass entry, $2 = generator (default: openssl rand -hex 32)
pass_ensure() {
	local entry="$1"
	local generator="${2:-openssl rand -hex 32}"
	local val
	val=$(pass "$entry" 2>/dev/null | head -n1) && [ -n "$val" ] && { echo "$val"; return; }
	val=$(eval "$generator")
	pass insert --echo "$entry" <<< "$val" >/dev/null 2>&1
	echo "$val"
}

# ── Fetch secrets from pass ────────────────────────────────────
LITELLM_KEY=$(p pjs/infra/litellm-master-key)

MINIO_ACCESS=$(p pjs/linode/object-storage-access-key)
MINIO_SECRET=$(p pjs/linode/object-storage-secret-key)

SOKETI_KEY=$(p pjs/search/soketi-app-key)
SOKETI_SECRET=$(p pjs/search/soketi-app-secret)

# SMTP — tender-info@datacraft.co.ke (Stalwart account: tender-info-datacraft)
# Stalwart authenticates by ACCOUNT NAME, not by email address.
SMTP_PASS=$(p pjs/mail/stalwart-tender-info-datacraft)
SMTP_AUTH_USER="tender-info-datacraft"
SMTP_FROM_ADDR="tender-info@datacraft.co.ke"

# App secrets — generate once, store in pass for repeatability
JWT_SECRET=$(pass_ensure pjs/docfusion/jwt-secret)
# MASTER_ENCRYPTION_KEY: base64-encoded 32-byte key read by DataEncryption
# (src/docfusion/security/encryption/data_encryption.py:589).
# Must be a base64 string; the Python code will base64-decode it to 32 bytes.
MASTER_ENCRYPTION_KEY=$(pass_ensure pjs/docfusion/master-encryption-key-b64 "openssl rand -base64 32 | tr -d '\n'")
NEXTAUTH_SECRET=$(pass_ensure pjs/docfusion/nextauth-secret)
TENANT_SECRET=$(pass_ensure pjs/docfusion/tenant-header-secret)

# Keycloak client — stored after manual Keycloak setup
KC_CLIENT_ID=$(p pjs/docfusion/keycloak-client-id 2>/dev/null || echo "SETUP_REQUIRED")
KC_CLIENT_SECRET=$(p pjs/docfusion/keycloak-client-secret 2>/dev/null || echo "SETUP_REQUIRED")

# ── DB creds — docfusion PostgreSQL role ───────────────────────
DB_USER="docfusion"
DB_PASS=$(p pjs/docfusion/db-password)

# ── Write .env ─────────────────────────────────────────────────
cat > "$OUT" <<ENV
# DocFusion .env — spare-2 (161.97.124.202)
# Generated by fill-env.sh — do NOT commit this file
#   scp deployment/.env.spare-2 root@161.97.124.202:/root/docfusion/.env

# ── Application ────────────────────────────────────────────────
DEBUG=false
LOG_LEVEL=info
NODE_ENV=production
NEXT_TELEMETRY_DISABLED=1
ENVIRONMENT=production

# ── Application secrets ────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
# Read by src/docfusion/security/encryption/data_encryption.py:589 as MASTER_ENCRYPTION_KEY
MASTER_ENCRYPTION_KEY=${MASTER_ENCRYPTION_KEY}
DOCFUSION_TENANT_HEADER_SECRET=${TENANT_SECRET}

# ── Database (db.lindela.io — PostgreSQL 17 PRIMARY) ───────────
DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db.lindela.io:5432/docfusion

# ── LiteLLM gateway (ml/vault — 62.169.25.77) ──────────────────
LITELLM_URL=http://62.169.25.77:4000/v1
LITELLM_KEY=${LITELLM_KEY}
# deepseek-v4-flash on Ollama cloud via LiteLLM — fast, JSON-reliable
LLM_MODEL=deepseek-v4-flash:0731-cloud
LLM_FAST_MODEL=deepseek-v4-flash:0731-cloud
TRIAGE_MODEL=deepseek-v4-flash:0731-cloud
LLM_EMBEDDING_MODEL=text-embedding-ada-002

# ── Discovery services (search — 84.247.181.100) ───────────────
SEARXNG_URL=http://84.247.181.100:8888
FIRECRAWL_URL=http://84.247.181.100:3002
DOCLING_URL=http://84.247.181.100:3600

# ── Notifications (Stalwart SMTP — mail.lindela.io) ────────────
DIGEST_TO_EMAIL=nyimbi@gmail.com
SMTP_HOST=mail.lindela.io
SMTP_PORT=587
# Stalwart authenticates by ACCOUNT NAME (not email); SMTP_FROM stays as address.
SMTP_USER=${SMTP_AUTH_USER}
SMTP_PASSWORD=${SMTP_PASS}
SMTP_FROM=${SMTP_FROM_ADDR}
SMTP_FROM_NAME="DocFusion Tender Intel"

# ── Cache (local Redis on spare-2) ──────────────────────────────
REDIS_URL=redis://127.0.0.1:6379/0
CACHE_URL=redis://127.0.0.1:6379/0

# ── Opportunity digest triage ───────────────────────────────────
OPPORTUNITY_PROFILE_PATH=/root/docfusion/config/opportunity_profile.yaml
TRIAGE_ENABLED=1
TRIAGE_BATCH_SIZE=25
CLOSING_SOON_DAYS=14
ENRICH_LIMIT=15
CRAWL_LIMIT=600
# SAM_API_KEY unset — DEMO_KEY fallback (register free key at sam.gov for full US coverage)

# ── Agent memory ────────────────────────────────────────────────
MEMORY_TTL_DAYS=30

# ── Storage (Linode E3 object store — docfusion-rfp bucket) ────
LINODE_E3_BUCKET=docfusion-rfp
LINODE_E3_REGION=gb-lon-1
LINODE_E3_ENDPOINT=https://gb-lon-1.linodeobjects.com
LINODE_E3_ACCESS_KEY_ID=${MINIO_ACCESS}
LINODE_E3_SECRET_ACCESS_KEY=${MINIO_SECRET}

# ── Soketi (WebSocket — 84.247.181.100:6001) ───────────────────
PUSHER_APP_KEY=${SOKETI_KEY}
PUSHER_APP_SECRET=${SOKETI_SECRET}
PUSHER_APP_ID=1
PUSHER_HOST=84.247.181.100
PUSHER_PORT=6001

# ── Auth (Keycloak — auth.lindela.io) ──────────────────────────
NEXTAUTH_URL=http://161.97.124.202:3000
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
KEYCLOAK_ISSUER=https://auth.lindela.io/realms/lindela
KEYCLOAK_CLIENT_ID=${KC_CLIENT_ID}
KEYCLOAK_CLIENT_SECRET=${KC_CLIENT_SECRET}
ENV

chmod 600 "$OUT"
echo "Written: $OUT"
grep -c "SETUP_REQUIRED" "$OUT" > /dev/null 2>&1 && {
	echo ""
	echo "⚠  Keycloak client not yet configured. To complete:"
	echo "   1. https://auth.lindela.io → realm lindela → Clients → Create"
	echo "      client_id=docfusion, access_type=confidential"
	echo "      valid_redirect_uris=http://161.97.124.202:3000/*"
	echo "   2. Copy the generated client secret, then:"
	echo "      printf 'docfusion' | pass insert pjs/docfusion/keycloak-client-id"
	echo "      printf '<secret>'  | pass insert pjs/docfusion/keycloak-client-secret"
	echo "   3. Re-run fill-env.sh and re-scp the .env"
} || true
