#!/usr/bin/env bash
# Populates deployment/.env.spare-2 from pass + OpenBao.
# Run: ./deployment/scripts/fill-env.sh
# Requires: pass, bao CLI

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/../.env.spare-2"

p() { pass "$1"; }  # shorthand

# ── Helper: generate+store a secret in pass if not present ─────
pass_ensure() {
	local entry="$1"
	if pass "$entry" &>/dev/null; then
		pass "$entry"
	else
		local val
		val=$(openssl rand -hex 32)
		printf '%s' "$val" | pass insert --echo "$entry"
		echo "$val"
	fi
}

# ── Fetch secrets from pass ────────────────────────────────────
LITELLM_KEY=$(p pjs/infra/litellm-master-key)

MINIO_ACCESS=$(p pjs/linode/object-storage-access-key)
MINIO_SECRET=$(p pjs/linode/object-storage-secret-key)

SOKETI_KEY=$(p pjs/search/soketi-app-key)
SOKETI_SECRET=$(p pjs/search/soketi-app-secret)

# SMTP — use hello@datacraft.systems (Stalwart)
SMTP_PASS=$(p pjs/mail/dada-hello-password)

# App secrets — generate once, store in pass for repeatability
JWT_SECRET=$(pass_ensure pjs/docfusion/jwt-secret)
ENCRYPTION_KEY=$(pass_ensure pjs/docfusion/encryption-key)
NEXTAUTH_SECRET=$(pass_ensure pjs/docfusion/nextauth-secret)
TENANT_SECRET=$(pass_ensure pjs/docfusion/tenant-header-secret)

# Keycloak client — stored after manual Keycloak setup
KC_CLIENT_ID=$(p pjs/docfusion/keycloak-client-id 2>/dev/null || echo "SETUP_REQUIRED")
KC_CLIENT_SECRET=$(p pjs/docfusion/keycloak-client-secret 2>/dev/null || echo "SETUP_REQUIRED")

# ── DB creds from OpenBao (only source with the actual password) ─
export BAO_ADDR="http://62.169.25.77:8200"
BAO_TOKEN=$(bao write -field=token auth/approle/login \
	role_id=78b01326-6401-e02e-b2c4-f329ad03c62d \
	secret_id=ea18d6e5-fad6-4155-5626-dfc826177c84)
export BAO_TOKEN
DB_USER=$(bao kv get -field=user secret/pjs/database/postgresql)
DB_PASS=$(bao kv get -field=password secret/pjs/database/postgresql)

# ── Write .env ─────────────────────────────────────────────────
cat > "$OUT" <<ENV
# DocFusion .env — spare-2 (161.97.124.202)
# Generated by fill-env.sh — do NOT commit this file
#   scp deployment/.env.spare-2 root@161.97.124.202:/root/docfusion/.env

# ── Application ────────────────────────────────────────────────
DEBUG=false
LOG_LEVEL=info
NODE_ENV=production
NEXT_TELEMETRY_DISABLED=1
ENVIRONMENT=production

# ── Application secrets ────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
DOCFUSION_TENANT_HEADER_SECRET=${TENANT_SECRET}

# ── Database (db.lindela.io — PostgreSQL 17 PRIMARY) ───────────
DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db.lindela.io:5432/docfusion

# ── LiteLLM gateway (ml/vault — 62.169.25.77) ──────────────────
LITELLM_URL=http://62.169.25.77:4000/v1
LITELLM_KEY=${LITELLM_KEY}
LLM_MODEL=gpt-4o
LLM_FAST_MODEL=gpt-4o-mini
LLM_EMBEDDING_MODEL=text-embedding-ada-002

# ── Discovery services (search — 84.247.181.100) ───────────────
SEARXNG_URL=http://84.247.181.100:8888
FIRECRAWL_URL=http://84.247.181.100:3002
DOCLING_URL=http://84.247.181.100:3600

# ── Notifications (Stalwart SMTP — mail.lindela.io) ────────────
DIGEST_TO_EMAIL=nyimbi@gmail.com
SMTP_HOST=mail.lindela.io
SMTP_PORT=587
SMTP_USER=hello@datacraft.systems
SMTP_PASSWORD=${SMTP_PASS}
SMTP_FROM=hello@datacraft.systems

# ── Agent memory ────────────────────────────────────────────────
MEMORY_TTL_DAYS=30

# ── Storage (Linode E3 object store — docfusion-rfp bucket) ────
LINODE_E3_BUCKET=docfusion-rfp
LINODE_E3_REGION=gb-lon-1
LINODE_E3_ENDPOINT=https://gb-lon-1.linodeobjects.com
LINODE_E3_ACCESS_KEY_ID=${MINIO_ACCESS}
LINODE_E3_SECRET_ACCESS_KEY=${MINIO_SECRET}

# ── Soketi (WebSocket — 84.247.181.100:6001) ───────────────────
PUSHER_APP_KEY=${SOKETI_KEY}
PUSHER_APP_SECRET=${SOKETI_SECRET}
PUSHER_APP_ID=1
PUSHER_HOST=84.247.181.100
PUSHER_PORT=6001

# ── Auth (Keycloak — auth.lindela.io) ──────────────────────────
NEXTAUTH_URL=http://161.97.124.202:3000
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
KEYCLOAK_ISSUER=https://auth.lindela.io/realms/pjs
KEYCLOAK_CLIENT_ID=${KC_CLIENT_ID}
KEYCLOAK_CLIENT_SECRET=${KC_CLIENT_SECRET}
ENV

chmod 600 "$OUT"
echo "Written: $OUT"
grep -c "SETUP_REQUIRED" "$OUT" > /dev/null 2>&1 && {
	echo ""
	echo "⚠  Keycloak client not yet configured. To complete:"
	echo "   1. https://auth.lindela.io → realm pjs → Clients → Create"
	echo "      client_id=docfusion, access_type=confidential"
	echo "      valid_redirect_uris=http://161.97.124.202:3000/*"
	echo "   2. Copy the generated client secret, then:"
	echo "      printf 'docfusion' | pass insert pjs/docfusion/keycloak-client-id"
	echo "      printf '<secret>'  | pass insert pjs/docfusion/keycloak-client-secret"
	echo "   3. Re-run fill-env.sh and re-scp the .env"
} || true
